### ISSUE TITLE
How to add to existing (Expo) project?

### ISSUE THREAD

**Issue by tomByrer** [tamagui/tamagui#1]
Hi, I was wondering if RNW was a bit slower than vanilla React, & glad I found your project!

I'm using the latest Expo; any tips to use this there?
Fortunately I'm focusing on getting XState to work with Expo, so I haven't really touched the styling yet.

TIA

**Comment by natew** [comment]
I'll try and set up an example for expo and see what I need to do. I'm not sure if it will support without ejecting. Am currently quite busy but I have a number of updates almost ready, maybe this coming weekend..

**Comment by natew** [comment]
Check it out: https://github.com/tamagui/tamagui-expo-example

**Comment by pafry7** [comment]
Hey @natew, we can't get that example working. Are there more steps required than installing packages & running?

**Comment by natew** [comment]
It runs for me but I'll check with latest published versions. I'm working on a new one with repack which helps me develop fully locally using yarn link, here: https://github.com/tamagui/tamagui-rn-repack-example

Note, this won't work for you for now, but going to use it to more rapidly fix up bugs with the demos and put together a kitchen sink demo set.

**Comment by natew** [comment]
I've published new versions of both, let me know if you run into anything.

**Comment by pafry7** [comment]
Hey @natew, I really appreciate your work. Expo example works, but after installing package `loader-utils` inside `@tamagui/static` (maybe you forgot) :)

**Comment by natew** [comment]
Thanks, should be fixed in latest versions.
