### ISSUE TITLE
Warning in React Native: transform[stderr]: Warning: Tamagui didn't find any valid components (DEBUG=tamagui for more)

### ISSUE THREAD

**Issue by sallar** [tamagui/tamagui#1019]
### Current Behavior

After upgrading to the latest version: 1.15.35, every time I'm starting the react native project, tamagui is showing this error for a lot of files:

```
transform[stderr]: Warning: Tamagui didn't find any valid components (DEBUG=tamagui for more)
```

And when I use `DEBUG=tamagui` this is what I get:

```
transform[stderr]: Warning: Tamagui didn't find any valid components (DEBUG=tamagui for more)
transform[stdout]: Time load-tamagui: 0ms
transform[stdout]: components [] []
transform[stdout]: {
transform[stdout]:   "doesUseValidImport": false,
transform[stdout]:   "hasImportedTheme": false
transform[stdout]: }
transform[stdout]:
transform[stdout]: END no styles
transform[stderr]: Warning: Tamagui didn't find any valid components (DEBUG=tamagui for more)
transform[stdout]: Time load-tamagui: 0ms
transform[stdout]: components [] []
transform[stdout]: {
transform[stdout]:   "doesUseValidImport": false,
transform[stdout]:   "hasImportedTheme": false
transform[stdout]: }
...
transform[stdout]: Ignoring file due to includeExtensions: /Users/sallar/Code/ug/ug-app/node_modules/color-name/index.js, includeExtensions: .ts, .tsx, .jsx
transform[stdout]: END no styles
transform[stdout]: Time load-tamagui: 0ms
transform[stdout]: components [] []
transform[stdout]: {
transform[stdout]:   "doesUseValidImport": false,
transform[stdout]:   "hasImportedTheme": false
transform[stdout]: }
```

### Expected Behavior

No errors or warnings should be shown

### Tamagui Version

```markdown
1.15.34
```

### Reproduction

```markdown
Just use Latest tamagui version is React Native.
```

**Comment by sallar** [comment]
I also get a lot of errors like this:

```
transform[stderr]: Error loading tamagui.config.ts (set DEBUG=tamagui to see full stack), running tamagui without custom config
transform[stdout]:
transform[stdout]:
transform[stdout]:     Converting circular structure to JSON
transform[stdout]:     --> starting at object with constructor 'Object'
transform[stdout]:     |     property 'Component' -> object with constructor 'Object'
transform[stdout]:     --- property 'staticConfig' closes the circle
transform[stdout]:
transform[stdout]:
```

**Comment by sallar** [comment]
Web version gives me more info:

```Tamagui Webpack Loader Error:
   Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'Component' -> object with constructor 'Object'
    --- property 'staticConfig' closes the circle
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'Component' -> object with constructor 'Object'
    --- property 'staticConfig' closes the circle
    at JSON.stringify (<anonymous>)
    at transformConfig (/Users/sallar/Code/ug/ug-app/node_modules/@tamagui/static/dist/cjs/extractor/generateTamaguiStudioConfig.js:66:32)
    at generateTamaguiStudioConfig (/Users/sallar/Code/ug/ug-app/node_modules/@tamagui/static/dist/cjs/extractor/generateTamaguiStudioConfig.js:46:22)
    at loadTamagui (/Users/sallar/Code/ug/ug-app/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:60:76)
    at async Object.load [as loadTamagui] (/Users/sallar/Code/ug/ug-app/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:89:42)
    at async extractToClassNames (/Users/sallar/Code/ug/ug-app/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/Users/sallar/Code/ug/ug-app/node_modules/tamagui-loader/dist/cjs/loader.js:69:23)
```

**Comment by sallar** [comment]
Just checked 1.15.33, it doesnt have this issue.

**Comment by mateitudose** [comment]
+1

**Comment by natew** [comment]
Actually will leave this open to confirm before.

We are slowing down releases and adding more tests. Apologies again for the turmoil

**Comment by natew** [comment]
I've verified this is fixed on the starter, let me know if it's working for you. Also if you can add `DEBUG=tamagui` and run and let me know the error, I added some extra logs to help debug what's happening here.

**Comment by sallar** [comment]
@natew I can confirm this is fixed now. Thank you.

Also I appreciate that you will slow down releases a little bit. This is a great project <3

**Comment by jwallet** [comment]
just installed this project with the version 1.36.6 and the issue came back, I downgraded to 1.15 and it's not there.
