### ISSUE TITLE
Custom Button with theme and variant doesn't have the correct background/color

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#1088]
### Current Behavior

I added custom themes like this: 
```ts
const light_primary = createTheme({
  mycolor: 'blue',
  mybg: 'red',
})

const light_primary_Button = createTheme({
  mycolor: 'white',
  mybg: 'tomato',
})
```

And created a `styled` Button like this:
```tsx
const MyButton = styled(Button, {
  name: 'Button',
  variants: {
    variant: {
      solid: {
        color: '$mycolor',
        backgroundColor: '$mybg',
      },
    },
  },
})
```
Then I'm using the component like this:
```tsx
export default function Page() {
  return (
    <Theme name="light">
      <YStack theme="primary" m="$6">
        <MyButton variant="solid">Test</MyButton>
      </YStack>
    </Theme>
  )
}
```

However the resulting button has tomato background and black text.

### Expected Behavior

Since the themes should be merging and on the button the final theme should be `light_primary_Button` and according to that theme, the button should have white text color.

### Tamagui Version

```markdown
1.22.3
```

### Reproduction

https://github.com/la55u/tama-variant-theme-bug
See the tamagui.config.ts and pages/index.tsx files

### System Info

```markdown
System:
    OS: Linux 6.2 Fedora Linux 37 (Workstation Edition)
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 9.38 GB / 31.04 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 3.5.0 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Firefox: 113.0b9
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.21.0 
    @manypkg/cli: ^0.19.1 => 0.19.2 
    check-dependency-version-consistency: ^3.0.3 => 3.0.3 
    eslint: ^8.21.0 => 8.39.0 
    node-gyp: ^9.3.1 => 9.3.1 
    prettier: ^2.7.1 => 2.8.8 
    turbo: ^1.8.3 => 1.9.3 
    typescript: ^4.7.4 => 4.9.5
```

**Comment by deggertsen** [comment]
I believe my issue is the same. Here's a screenshot and a repro.
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/3967142/235473075-99f27c0a-468a-4777-a674-55524d29aad8.png">
https://github.com/deggertsen/tamagui-button-bug-repro

**Comment by natew** [comment]
Please check on v1.22.6

**Comment by la55u** [comment]
I upgraded my reproduction in the original issue and the issue is still present on web:/

**Comment by natew** [comment]
`color` doesn't work on Button directly, that only exists on ButtonText, which maybe why you are running into this. I can't replicate, I added another test basically identical to this.

**Comment by la55u** [comment]
I know but it somehow worked in previous versions of Tamagui. Do you mean rhe the repro I made doesn't work for you?

**Comment by deggertsen** [comment]
I have upgraded my repro repo above to 1.22.7 and the issue still hasn't gone away. You should be able to pull that repo to reproduce.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/3967142/235660646-9a779191-c64e-4ec3-ad0d-dd3d7ba95328.png">

**Comment by deggertsen** [comment]
Created an [UpdatedButton.tsx](https://github.com/deggertsen/tamagui-button-bug-repro/blob/main/packages/ui/src/UpdatedButton.tsx) that attempts to match the current Button docs as closely as possible while adding a forwardRef. Seems to work better, but I'm getting a typscript error that I have to @ts-ignore. Some of the other styling doesn't seem to be getting picked up, but I'm guessing it's because I don't have it setup quite right. I'll see if I can resolve that part.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/3967142/235663885-dc9f8bd5-36d9-40aa-947e-dedff2d90986.png">

**Comment by natew** [comment]
Lets re-open with a new issue and if you do have a repro can you fork this repo and reproduce it in the kitchen-sink? I think the latest versions are fixed as far as a I can tell.

**Comment by la55u** [comment]
Unfortunately it's still broken on web. This is all you need for the reproduction (pushed the upgrade to my repo too):
![image](https://user-images.githubusercontent.com/30611343/235871199-22390015-e79e-4100-a502-ad93a02b89ce.png)
![image](https://user-images.githubusercontent.com/30611343/235871668-471c5f20-9ea7-42ad-a02d-0d84d1bf41bd.png)

**Comment by natew** [comment]
You can’t set color directly like that, Tamagui works like react native in that it separates text from view. That it works on the types just shows that we destined the button wrong. We’re fixing this by redesigning the button to be split into Button and Button.Text. 

Follow the advanced customization guide for now and set the color on Text and the background on the Frame.

**Comment by natew** [comment]
It is possible I could make some sort of exception here but it would be pretty complex and again this API is not how we want it to be going forward. The radix style API is coming soon it’s in a PR. Until then you can work around through advanced customization guide.

**Comment by la55u** [comment]
Okay understandable, no need for exception. But my only issue is that the advanced customization guide doesn't show how to use variants. Do I need to spacify the same variants in both Frame and Text? Or will they be picked up automatically? Do I need to pass it to `useButton` somehow? Kinda lost here..

**Comment by deggertsen** [comment]
Here's an example of varients:
```const CustomButtonFrame = styled(ButtonFrame, {
  variants: {
    circular: {
      true: {
        padding: '$0',
        paddingLeft: 1,
        height: '$5',
        width: '$5',
        maxHeight: '$5',
        maxWidth: '$5',
        borderRadius: '$10',
        alignItems: 'center',
        justifyContent: 'center',
      },
    },
    wrapper: {
      true: {
        padding: 0,
        margin: 0,
        height: 'unset',
        width: 'unset',
        borderRadius: 'unset',
        alignItems: undefined,
        justifyContent: undefined,
      },
    },
  },
})
```

**Comment by sallar** [comment]
I have the same issue.
As soon as I set a theme for `Button`, the theme for `SystemText` stops working.

so this works:

```ts
const themes = {
  // ...
  dark_ButtonText: {
    color: 'red'
  }
}
```

but the following doesnt work. the button gets a blue background, but the color for the text resets to default.

```ts
const themes = {
  // ...
  dark_Button: {
    background:  'blue'
  }
  dark_ButtonText: {
    color: 'red'
  }
}
```
