### ISSUE TITLE
Android: Talkback screenreader prevents styled buttons from being (double) tappable

### ISSUE THREAD

**Issue by mjphillips-sg** [tamagui/tamagui#1284]
### Current Behavior

If you use a styled button, it's not tappable when talkback is enabled.  iOS works as expected.

For full reference, this is our styled button implementation:

```tsx
import { Button as TButton, getTokens, styled } from "tamagui";

const tokens = getTokens();

const Button = styled(TButton, {
	borderRadius: tokens.radius.$true.val,
	padding: 8,
	shadowRadius: 4,
	shadowOpacity: 0.15,
	shadowOffset: { width: 0, height: 4 },
	shadowColor: "black",
	backgroundColor: "$primary",
	borderWidth: 0,
	fontWeight: "700",
	color: "white",
	variants: {
		secondary: {
			true: {
				backgroundColor: "$secondary",
				color: "white",
			},
		},
		outlined: {
			true: {
				backgroundColor: "transparent",
				borderColor: "$borderColor",
				borderWidth: 1,
				color: "$color",
			},
		},
		danger: {
			true: {
				backgroundColor: "$red",
				color: "white",
			},
		},
	} as const,
});

export default Button;
```

### Expected Behavior

Button should be tappable

### Tamagui Version

```markdown
1.29.1
```

### Reproduction

```markdown
With a react native application + tamagui, create a styled/variant button.   


Turn on talkback, notice the button is not tappable.


I believe you need a physical device to turn on talkback and reproduce.


Note: talkback makes the phone very difficult to use, I highly recommend this link to manage the feature: https://support.google.com/accessibility/android/answer/6007100?sjid=10925463207668602077-NA#option_1
```

### System Info

```markdown
N/A
```

**Comment by TheEhsanSarshar** [comment]
add `accessibilityRole: "button"`
and if not works then also add `accessible`

**Comment by TheEhsanSarshar** [comment]
so you mean on double tap it doesn't trigger onPress callback ?
does it say "double tap to click" ?

**Comment by TheEhsanSarshar** [comment]
maybe you made parent of the button an accessible component, set accessible=false on the parent

**Comment by mjphillips-sg** [comment]
As a work around in the meantime we simply ported the styled variant to a component:

```tsx

import { ButtonProps, Button as TButton, getTokens } from "tamagui";

export default function Button(
	props: ButtonProps & {
		secondary?: boolean;
		outlined?: boolean;
		danger?: boolean;
		disable?: boolean;
	},
) {
	let computedProps = {
		...props,
		padding: 8,
		shadowRadius: 4,
		shadowOpacity: 0.15,
		shadowOffset: { width: 0, height: 4 },
		shadowColor: "black",
		backgroundColor: "$primary",
		borderWidth: 0,
		fontWeight: "700",
		color: "white",
	};

         // Implementation of prop merging omitted for brevity 

         return <TButton {...computedProps}>{props.children}</TButton>;

}

```

I also wanted to point out this issue impacts all Tamagui styled components, like `Circle` or `Square`.  If they contain an `onPress` property it will not trigger when using Talkback on Android.

**Comment by bluedaniel** [comment]
Is anyone looking into a fix for this? We are retroactively adding accessibility to a large app and this is a big concern for us

**Comment by natew** [comment]
Anyone know what the issue is here? Happy to make the change but what exactly makes it not trigger? Do we need to pass it to pressaibility differently? We also fixed a few accessibility props lately so perhaps working now.

**Comment by mjphillips-sg** [comment]
I'll try to test this today and report back, thanks @natew

**Comment by mjphillips-sg** [comment]
It still does not work. 

Once talkback is on you have to double tap everything to get the tap event to fire. If you tap once it reads the button contents (this works fine).  

Is there anything that could be interfering with the **double** tap event? Again, this is only for a styled component.  If I wrap a tamagui button in another component it works fine as noted in the workaround on 6/13.

**Comment by alitnk** [comment]
So if I understand it correctly, this issue states that when using Talkback, onPress is not called when you double tap, when a custom styled button is focused. 
We don't really recommend using `styled()` on `Button` itself - we recommend this guide to make custom buttons: https://tamagui.dev/docs/guides/how-to-build-a-button

Everything seems to be working with a proper button setup:

https://github.com/tamagui/tamagui/assets/35243344/97f8c571-da13-41e3-9a2c-c6f0eb833fc4

(Sorry for the low quality video, GitHub kept complaining about the size)

I'm closing the issue but feel free to re-open if this is still an issue.
