### ISSUE TITLE
FontFamily not being passed through to Tamagui Text components (Text, SizableText, Paragraph)

### ISSUE THREAD

**Issue by NavyAnt24** [tamagui/tamagui#1483]
### Current Behavior

I am using the Google fonts, specifically this library: `@expo-google-fonts/alex-brush`.

Let's say you have code like this:

```
<SizableText
    fontSize={tamaguiSize.$6}
    lineHeight={tamaguiSize.$7}
    style={{ fontFamily: 'AlexBrush_400Regular' }}
>
    HELLO!
</SizableText>
```

The `fontFamily` in the `style` attribute is not being passed to the underlying native `Text` component. I did try putting the `color` attribute into the `style` attribute, and it did work. So I think at least some attributes are getting passed through. I also tried using Tamagui's `<Text>` component, and I had the same issue.

Similarly, adding the fontFamily attribute to the Tamagui component doesn't work and leads to a TypeScript error.
```
<SizableText
    fontSize={tamaguiSize.$6}
    lineHeight={tamaguiSize.$7}
    fontFamily="AlexBrush_400Regular"
>
    HELLO!
</SizableText>
->
Type '"AlexBrush_400Regular"' is not assignable to type 'Variable<any> | FontTokens | undefined'.
```

I also get this error when using the fontFamily attribute: `Warning: No font found. For a sized text component, you either need to set fontFamily directly, or through the "defaultFont" setting in your createTamagui config.`

However, I do not want to change the defaultFont, as I only want to use my Google font in specific places in the app.

One fix is to use react-native's `<Text>` component. In this case, defining the style as the `@expo-google-fonts` documentation recommends works fine:
```
<Text style={{ fontFamily: 'AlexBrush_400Regular', fontSize: 40 }}>IT WORKS!</Text>
```

### Expected Behavior

I would expect the `fontFamily` within the `style` attribute of Tamagui text components to override the default font. Furthermore, I would also expect the `fontFamily` attribute itself, on Tamagui text components, to override the default font, even if it is not within the `style` attribute.

### Tamagui Version

```markdown
1.45.10
```

### Reproduction

```markdown
import { Pressable, Text } from 'react-native'
import { Paragraph, Stack, YStack } from '@my/ui' // Based upon Tamagui's solito-starter


<Paragraph
  fontSize={tamaguiSize.$6}
  lineHeight={tamaguiSize.$7}
  style={{ fontFamily: 'AlexBrush_400Regular' }}
>
  It doesn't work :-(
</Paragraph>
<Text style={{ fontFamily: 'AlexBrush_400Regular', fontSize: 40 }}>It does work!</Text>
{/* Notice that the second component is React Native's native Text component. */}
```
```


### System Info

_No response_

**Comment by 0xsj** [comment]
Is this the same case for both native + web? 
For custom fonts I had to create a separate font.native.ts file that @required at the otf , ttf files I intended to use 
.

**Comment by NavyAnt24** [comment]
I have not tried this on web (having trouble getting it to start), but I think web may be a separate issue. Correct me if I'm wrong, but I don't think we actually have font parity between native and web...? Because the App component in apps/expo/App.tsx looks something like this:

```
export default function App() {
  const [loaded] = useFonts({
    Inter: require('@tamagui/font-inter/otf/Inter-Medium.otf'),
    InterBold: require('@tamagui/font-inter/otf/Inter-Bold.otf'),
    AlexBrush_400Regular,
  })

  if (!loaded) {
    return null
  }
```

So we're pulling the required fonts into Expo, but I imagine for web I'll need to manually pull them in like you mentioned.

**Comment by 0xsj** [comment]
For example, the situation I ran into was when I was trying to use the silkscreen font. 

in expo, I had to import a fonts.native.ts file in app.tsx.
`const [loaded] = useFonts(customFonts);`

in nextjs, I had to make an import statement at top level to use the css files that was associated with the custom font. 
`import '@tamagui/font-silkscreen/css/400.css';`

**Comment by NavyAnt24** [comment]
Yes, I think I'd have to do something similar on web as well. But I would expect things to work out of the box in native.

**Comment by nDeavor9** [comment]
This is happening to me as well. I am using Expo 48 with managed workflow. I bumped tamagui from 1.30.22 to 1.48.5 and the styles for Text component are gone. I was using custom font from @expo-google-fonts/plus-jakarta-sans and configured them through theme. But all the Heading tags like H1,H2 etc., has the font family, font size and other styles intact.

@natew Hey, sorry for the direct mention. I did a bit of trial-and-error and found that the issue seems to be happening after [v1.39.8](https://github.com/tamagui/tamagui/releases/tag/v1.39.8). 
v1.39.7 is working as intended. 
Hopefully this helps.

**Comment by natew** [comment]
I thought i fixed this but maybe somehow it regressed again. @alitnk will be on it today for a bit too

**Comment by alitnk** [comment]
Hey, are you guys sure you're getting this results on latest (v1.48.7)? Here's what I'm getting:
<img width="1216" alt="image" src="https://github.com/tamagui/tamagui/assets/35243344/081b80b5-8e86-46c6-9663-8ade957b8544">

Having set up `useFonts` like so:
```tsx
import { AlexBrush_400Regular } from '@expo-google-fonts/alex-brush';
// ...
const [loaded] = useFonts({
  AlexBrush_400Regular,
})
```

Passing `fontFamily="AlexBrush_400Regular"` to `<Paragraph` would give TS issues of course, because it accepts theme fonts (e.g. `fontFamily="$alexBrush"`)

**Comment by alitnk** [comment]
Hey, are you guys sure you're getting this results on latest (v1.48.7)? Here's what I'm getting:
<img width="1216" alt="image" src="https://github.com/tamagui/tamagui/assets/35243344/081b80b5-8e86-46c6-9663-8ade957b8544">

Having set up `useFonts` like so:
```tsx
import { AlexBrush_400Regular } from '@expo-google-fonts/alex-brush';
// ...
const [loaded] = useFonts({
  AlexBrush_400Regular,
})
```

Passing `fontFamily="AlexBrush_400Regular"` to `<Paragraph` would give TS issues of course, because it accepts theme fonts (e.g. `fontFamily="$alexBrush"`)

**Comment by nDeavor9** [comment]
As for me, for customising the theme, I have given this:
`
fonts: {
    heading: plusJakartaFont,
    body: plusJakartaFont
  }
`
where, this is plusJakartaFont:
```
const plusJakartaFont = createFont({
  family: 'Plus-Jakarta-Sans-Regular',
  size: {
    '2xs': 10,
    xs: 12,
    sm: 14,
    md: 14,
    lg: 16,
    xl: 18,
    '2xl': 22,
    '3xl': 26,
    '4xl': 30,
    '5xl': 34,
    '6xl': 40,
    '7xl': 48,
    '8xl': 56,
    '9xl': 64,
    true: 14,
    3: 15,
    // ...
  },
  lineHeight: {
    1: 17,
    2: 22,
    3: 25,
    4: 30,
    5: 40,
    // ...
  },
  weight: {
    4: '300',
    6: '600',
    light: '300',
    normal: '400',
    regular: '500',
    semibold: '600',
    bold: '700',
  },
  letterSpacing: {
    1: 0.25,
    2: 0.5,
    3: 0.75,
    4: 1,
  },

  face: {
    300: { normal: 'Plus-Jakarta-Sans-Light', italic: 'Plus-Jakarta-Sans-Light-Italic' },
    400: { normal: 'Plus-Jakarta-Sans-Regular', italic: 'Plus-Jakarta-Sans-Regular-Italic' },
    500: { normal: 'Plus-Jakarta-Sans-Medium', italic: 'Plus-Jakarta-Sans-Medium-Italic' },
    600: { normal: 'Plus-Jakarta-Sans-SemiBold', italic: 'Plus-Jakarta-Sans-SemiBold-Italic' },
    700: { normal: 'Plus-Jakarta-Sans-Bold', italic: 'Plus-Jakarta-Sans-Bold-Italic' },
  },
});
```
I loaded the fonts using Font.LoadAsync from expo-font, and then render the app. 
```
Font.loadAsync({
          'Plus-Jakarta-Sans-Light': PlusJakartaSans_300Light,
          'Plus-Jakarta-Sans-Regular': PlusJakartaSans_400Regular,
          'Plus-Jakarta-Sans-Medium': PlusJakartaSans_500Medium,
          'Plus-Jakarta-Sans-SemiBold': PlusJakartaSans_600SemiBold,
          'Plus-Jakarta-Sans-Bold': PlusJakartaSans_700Bold,
          'Plus-Jakarta-Sans-Light-Italic': PlusJakartaSans_300Light_Italic,
          'Plus-Jakarta-Sans-Regular-Italic': PlusJakartaSans_400Regular_Italic,
          'Plus-Jakarta-Sans-Medium-Italic': PlusJakartaSans_500Medium_Italic,
          'Plus-Jakarta-Sans-Italic-SemiBold': PlusJakartaSans_600SemiBold_Italic,
          'Plus-Jakarta-Sans-Italic-Bold': PlusJakartaSans_700Bold_Italic,
        })
```
It used to work perfectly without manually giving anything till 1.39.7.

I just noticed that the catch here is that I have to manually give fontFamily: '$body' everywhere I use a text component, and it works fine. I was just confused why it worked without anything previously and now I had to introduce a declaration. 

Anyways, If you guys think this is normal, I'll start giving font family manually. Thanks for your time.

**Comment by alitnk** [comment]
@nDeavor9 That sounds like your `defaultFont` isn't set properly. We've had some changes there. Can you check your Tamagui config to see if there's a default font set? Setting the default font to `body` should be working for you (if your font's name is registered as body)

**Comment by nDeavor9** [comment]
@alitnk
Tried setting defaultFont: 'body', still doesnt work with providing font family to text components. It just shows a default font family of 'Times' and all the styles are gone like fontWeight and fontSize.

**Comment by alitnk** [comment]
@nDeavor9 - A simple reproduction repo would help a lot. Can't get it to break unfortunately.

@NavyAnt24 - Is this still an issue on the latest? see my other comment https://github.com/tamagui/tamagui/issues/1483#issuecomment-1659941255.

**Comment by etemesgen** [comment]
> Hey, are you guys sure you're getting this results on latest (v1.48.7)? Here's what I'm getting: <img alt="image" width="1216" src="https://user-images.githubusercontent.com/35243344/257470827-081b80b5-8e86-46c6-9663-8ade957b8544.png">
> 
> Having set up `useFonts` like so:
> 
> ```tsx
> import { AlexBrush_400Regular } from '@expo-google-fonts/alex-brush';
> // ...
> const [loaded] = useFonts({
>   AlexBrush_400Regular,
> })
> ```
> 
> Passing `fontFamily="AlexBrush_400Regular"` to `<Paragraph` would give TS issues of course, because it accepts theme fonts (e.g. `fontFamily="$alexBrush"`)

This works but i don't know for any reason it doesn't work on Buttons, would you have any idea ?

**Comment by pedrosantosobral** [comment]
> @nDeavor9 - A simple reproduction repo would help a lot. Can't get it to break unfortunately.
> 
> @NavyAnt24 - Is this still an issue on the latest? see my other comment [#1483 (comment)](https://github.com/tamagui/tamagui/issues/1483#issuecomment-1659941255).

Im having the exact same issue that @nDeavor9 is having:

if I add $body to the fontFamily prop it works like a charm, just does not work as default, even having it set as the default font

I'm on the latest tamagui 1.49

**Comment by natew** [comment]
Can you all make sure the fontFamily is quoted, like so:

```
'"Source Sans 3", -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif' not 'Source Sans 3, -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif'
```

We need to fix the Takeout generation scripts to quote spaced font families, so this may be the cause! On web at least.

**Comment by pedrosantosobral** [comment]
<img width="478" alt="Screenshot 2023-08-23 at 21 12 51" src="https://github.com/tamagui/tamagui/assets/33328797/d1a57b8b-f438-4224-b3c5-98189fc4a7af">
<img width="321" alt="Screenshot 2023-08-23 at 21 13 24" src="https://github.com/tamagui/tamagui/assets/33328797/d9195629-56e3-4376-8587-59b6e542c37f">

<img width="338" alt="Screenshot 2023-08-23 at 21 13 14" src="https://github.com/tamagui/tamagui/assets/33328797/8f62801d-1f3b-4cad-88fe-daed3f302c50">

@natew its currently working only applying the font family manually, the defaultFont is not working, even going with your suggested '"FigtreeRegular"' quotes.

**Comment by natew** [comment]
You shouldn't use `style` btw just use regular prop `fontFamily`, the `style` attribute is considered a bailout that acts just like normal style property and doesn't interact with any Tamagui stuff.

I think there's some issues happening on this ticket but lets re-open with a solid repro so we can fix it.

**Comment by copterisimo** [comment]
Hey, pondered between opening a new issue and just reviving this since it has all this history, decided for the latter hope its ok.

I have this exact issue on current release 1.76.0

Environment:

- Web: Vite@4.3.0

Reproduction:

1. Simply install the sample project with npm create tamagui@latest
2. Edit src/Root.tsx to include two Text components as follows:
`
    <TamaguiProvider config={config} defaultTheme="light">
      <YStack f={1} ai="center" jc="center">
        <Text fontFamily='$body' fontSize={50}>Hello world</Text>
        <Text fontSize={50}>Hello world</Text>
      </YStack>
    </TamaguiProvider>
`

3. Run yarn dev:vite
4. Notice how both text components render differently, one with a font family and one with default browser's font.

I believe this is the best way to explain this issue since it uses the sample project as reproduction repo.

In native, this works correctly and you may skip the fontFamily prop for all Text components.
