### ISSUE TITLE
[Web] Select scrolling issue for small lists

### ISSUE THREAD

**Issue by kzlar** [tamagui/tamagui#1519]
### Current Behavior

![repro](https://github.com/tamagui/tamagui/assets/120426485/1bc30cfe-cff2-4a5e-b87e-b498860a3660)

See attached GIF, by hovering over the popover select and scrolling, the popover changes position and is no longer attached to the base component.
Setting `disableScrolling` does not help.

### Tamagui Version

```markdown
latest
```

### Reproduction

```markdown
The GIF above was captured from vanilla latest tamagui, running `yarn sandbox` and adding a plain non-native select straight from the docs. The only change is that the list is small (3 items).
```

**Comment by kzlar** [comment]
Seems to be fixed in v1.53.1, thanks!

**Comment by lisitsyna-anna** [comment]
Hi! How did you fix it?  Adding `disableScroll` to the `Select.Viewport` didn't help

**Comment by kzlar** [comment]
Was fixed by v1.53.1, didnt have to do anything.
If you're able to reproduce it, create an example repo and create a new ticket for the team.

**Comment by lisitsyna-anna** [comment]
@kzlar Thanks!

**Comment by Bliqui** [comment]
The issue still exists on `1.76.0`. By the way, this issue could be reproduced on the tamagui documentation site, in the section with an example of using the `Select` component
