### ISSUE TITLE
Icons not inheriting group styles

### ISSUE THREAD

**Issue by jbean96** [tamagui/tamagui#1707]
### Current Behavior

Icons don't inherit group styles `$group-X-hover` like other components do. 

### Expected Behavior

Icons behave the same way as other components and can inherit the group styles.

I understand that this likely would have to do with the implementation of `themed`. Ours is very much derived from Tamaguis so I figured I'd verify that it was a Tamagui issue.

### Tamagui Version

```markdown
1.71.0
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
- Clone [this repo](https://github.com/jbean96/tamagui-icon-groups)
- Setup:
  - `yarn`
  - `yarn watch:build`
  - `yarn sandbox`
- Visit `localhost:9000`
- Hover over box in the center, observe that the icon doesn't turn white like the text even though they are configured the same.
```

### System Info

```markdown
System:
    OS: macOS 13.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 247.50 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.6.0 - ~/.nvm/versions/node/v19.6.0/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - ~/.nvm/versions/node/v19.6.0/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 116.0.5845.187
    Firefox: 114.0.1
    Safari: 16.6
  npmPackages:
    @biomejs/biome: ^1.2.2 => 1.2.2
    @manypkg/cli: ^0.19.1 => 0.19.2
    @nderscore/tamagui-typescript-plugin: ^0.3.1 => 0.3.1
    @vercel/og: ^0.5.8 => 0.5.8
    check-dependency-version-consistency: ^3.0.3 => 3.0.3
    import-sort-style-module: ^6.0.0 => 6.0.0
    npm-run-all: ^4.1.5 => 4.1.5
    p-map: ^5.5.0 => 5.5.0
    prettier: ^2.8.1 => 2.8.8
    pretty-quick: ^3.1.2 => 3.1.3
    prompts: 2.1.0 => 2.1.0
    turbo: ^1.10.13 => 1.10.13
    typescript: ^5.2.2 => 5.2.2
    ultra-runner: ^3.10.5 => 3.10.5
```

**Comment by natew** [comment]
this maybe fixed in latest versions as we use usePropsAndStyle now, let me know

**Comment by jbean96** [comment]
> this maybe fixed in latest versions as we use usePropsAndStyle now, let me know

@natew I just rebased onto the latest `master` and it looks like it's still an issue. It's possible I didn't setup my `Sandbox` correctly but I think I implemented the repro with a valid usage of groups.

**Comment by natew** [comment]
Tested locally and on create-app and its working:

![CleanShot 2023-10-22 at 20 02 37@2x](https://github.com/tamagui/tamagui/assets/12100/7d52ccc0-6d87-46bb-9d06-822959d61363)

**Comment by jbean96** [comment]
Hey @natew, I updated my forked repo of `master` today and the problem still exists. 

Note in the description that this was referring to pseudo styles like `-hover` and `-pressed`, I agree that just doing non-pseudo styles works fine.

**Comment by arekkubaczkowski** [comment]
@jbean96  @natew  I am having the same issue. Moreover, I am facing strange typescript error when I pass "group" prop to any Tamagui component. The group works itself but have no idea how to solve that TS error.

<img width="1037" alt="Screenshot 2024-01-09 at 10 08 37" src="https://github.com/tamagui/tamagui/assets/18654447/08a87aeb-e473-4554-9a7e-01d51ac7afc8">
