### ISSUE TITLE
Bug: Not possible to subscribe to group pseudo state without trickery (WEB)

### ISSUE THREAD

**Issue by nderscore** [tamagui/tamagui#1945]
### Current Behavior

When using the "group" props feature of tamagui, it's not possible to directly subscribe to group pseudo state changes on the web platform.

Initially, I tried to naively subscribe to the `ComponentContext` from tamagui like this:

```tsx
const { groups } = useContext(ComponentContext.context)
const pseudoState = groups.groupName?.pseudoState
```

But changes to the pseduo state did not trigger re-renders for consumers of this context.

---

After looking a little deeper into the implementation of the group prop feature, I noticed there is a `subscribe` method on the `groups` property of the component context, so I wrote a [custom hook to subscribe to changes based on group name](https://github.com/nderscore/tamagui-starter-free/blob/bug-group-pseudo-subscribe/packages/ui/src/useGroupPseudoState.ts).

Doing this doesn't work on the web though, because there the values of these state changes are optimistically ignored under normal circumstances, when `runtimeHoverStyle`/`runtimePressStyle`/etc are not true here:

https://github.com/tamagui/tamagui/blob/v1.79.6/packages/web/src/createComponent.tsx#L944-L959

To work around this, it's possible to pass empty functions for the `onPress` or `onHoverIn` props, which bypasses the conditions that prevent the values of pseudo-state updates from being set.

---

After resolving that issue, I ran into the issue described by #1937 - subscriptions are not managed independently for each instance of a group, so a hover on one group triggers changes on all groups.

### Expected Behavior

Pseudo state updates should not be hidden on the web platform when group subscribers exist.

Subscribers to group context changes should only receive updates from their parent component, not from any component that implements that group name.

### Tamagui Version

```markdown
1.79.6 and prior
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

I've created a minimal reproduction on a fork of the starter template. The branch name is `bug-group-pseudo-subscribe`:

https://github.com/nderscore/tamagui-starter-free/tree/bug-group-pseudo-subscribe

**Comment by natew** [comment]
We've fixed the issue with group context. I actually didn't even know component context was visible externally tbh, it's meant to be an internal thing, but happy to land any fixes if you want to take them on. I haven't checked the repro yet is it still relevant with the fixes to overlapped contexts?

**Comment by nderscore** [comment]
@natew Just took a look at this again on `1.79.19`...

I no longer see the issue described by #1937 but the rest of this ticket is still happening.

On web, it's still not possible for a component to arbitrarily subscribe to group pseudo state unless you trick the library into adding runtime event handlers.

> I actually didn't even know component context was visible externally tbh, it's meant to be an internal thing, but happy to land any fixes if you want to take them on.

Yeah, [my custom `useGroupPseudoState` hook](https://github.com/nderscore/tamagui-starter-free/blob/bug-group-pseudo-subscribe/packages/ui/src/useGroupPseudoState.ts) would probably make more sense to be part of Tamagui itself. I only started digging around in the internals because I didn't see any publicly-exposed way to listen to group pseudo state changes. :sweat_smile:

**Comment by natew** [comment]
I don't think supporting group listening was on my radar, what's the use case? If we did add a hook or something we'd want it in a separate package or something. Stuff like this always makes me want to make core pluggable so we can keep it light and add things easily.

**Comment by nderscore** [comment]
In my case, I want to [update the `color` prop of a non-styled component (an SVG icon)](https://github.com/nderscore/tamagui-starter-free/blob/bug-group-pseudo-subscribe/packages/ui/src/NavButton.tsx#L75-L84) on either hover or press.

---

I guess an alternative approach might look something like this?

```tsx
const style = useStyle({
  color: '$color',
  '$group-navbutton-hover': {
    color: '$blue8',
  },
  '$group-navbutton-press': {
    color: '$blue8',
  },
});
// pass style.color as `color` prop
```

But I don't think `useStyle` supports group styles.

**Comment by kzlar** [comment]
Encountering the same issue: https://discord.com/channels/909986013848412191/974145843919716412/1189430877093117963
I can confirm that `usePropsAndStyle` doesn't work with group pseudo styles.

**Comment by natew** [comment]
Sounds like fixing `usePropsAndStyle` to support groups is an obvious win, which should then fix icons I believe. We should add some tests around the runtime behavior of groups as well.

**Comment by nderscore** [comment]
I thought of an idea while chatting about this on discord last night.

Even if `usePropsAndStyle` supported groups - it's still not an ideal way to handle psuedo-state styling on the web, since the event handlers could be out of sync with the CSS hover state.

Another way to solve this could be adding first-class support to Tamagui for styling `react-native-svg` components. `styled()` could have another config option that enables SVG style properties like `fill` and `stroke`. This could resolve to CSS classnames on the web, and on native it could pass them through as props to the component.

```tsx
import { Svg } from 'react-native-svg'
const StyledSvg = styled(Svg, {
  width: '$4',
  height: '$4',
  stroke: '$color4',
}, {
  isSvg: true // enables SVG style props like 'fill' / 'stroke'
})
```

Then the icon component libraries could be proper styled components.

**Comment by natew** [comment]
Yea this would be nice too. We could add instead of isSvg something like { propType: { fill: “size” } } as the second argument

**Comment by natew** [comment]
Attempted here: https://github.com/tamagui/tamagui/commit/ce7a963fd48713af9c1738ccb83e0431bf1e46bf

**Comment by kzlar** [comment]
@natew wondering if that could be incorporated into `themed`? kinda hoping to resolve the group-based icon coloring without wrapping my icons in `styled`. Of course I mean that in addition to being able to wrap svg in `styled`, since that would be awesome for other use cases.

**Comment by natew** [comment]
If you want to send a PR testing that out would be nice!

**Comment by kzlar** [comment]
@natew sure - do you mean something like this: https://github.com/tamagui/starter-free/compare/main...kzlar:starter-free:repro/issue_1945
Current behavior is the icon stays black even when you hover the green stack, expected behavior is for the icon to turn red when you hover the green stack. Ideally with no other change (since all icons are already wrapped by `themed` I guess it would be something there?)
Let me know if you meant a PR somewhere else.
