### ISSUE TITLE
Styled button make press event sound two times.

### ISSUE THREAD

**Issue by Hardik-Adroja** [tamagui/tamagui#2285]
### Current Behavior

Styled tamagui button make press event sound double time, normal tamagui button works fine.

### Expected Behavior

OnPress event sound should be once only for styled button also. 

### Tamagui Version

```markdown
Tamagui Version: 1.89.28
```

### Platform (Web, iOS, Android)

```markdown
Expo go (In Android)
```

### Reproduction

```markdown
https://github.com/Hardik-Adroja/Tamagui-demo.git
```

**Comment by OleksiiKalinin** [comment]
@Hardik-Adroja , hi, did you find a reason and solution?

**Comment by Carter-Apas** [comment]
Think we have this problem too, any solutions?

**Comment by natew** [comment]
Still an issue?

**Comment by natew** [comment]
This was an expo thing I believe and should be fixed

**Comment by JxavierP** [comment]
This is not fixed. Booted up a brand new project and the problem is still there.

**Comment by cgorrieri** [comment]
I still have the issue and I am on the latest expo 53 and latest tamagui.
Is there a way to disable the sound?
