### ISSUE TITLE
The expo-router starter gets stuck when started & strange fix

### ISSUE THREAD

**Issue by iyibu** [tamagui/tamagui#2429]
### Current Behavior

The current Expo Router starter created by the community indeed gets stuck by default, and there's a peculiar workaround for the freezing problem.

_workaround fix_: (BUT WHY?)
If you export Tamagui components (such as Text, View, etc.) used under the **app** from outside the **app** like this: 

`export { Text, View } from 'tamagui'` (./components/ui/index.tsx)

`import { Text, View } from '@components/ui'` (./app/(tabs)/_layout.tsx)

you won't encounter any issues.

So, it's necessary not to directly use "tamagui" under the **app** directory.

### Expected Behavior

If you try it out, you will notice that the terminal remains in a state like the following:

Web C:\Users\\\*\*\*\works\expo-router\node_modules\expo-router/entry.js ▓▓▓▓▓▓░░░░░░░░░░ 41.4% (317/513)
Server C:\Users\\\*\*\*\works\expo-router\node_modules\expo-router\node/render.js ▓▓▓▓▓▓▓▓▓░░░░░░░ 59.0% (415/566)

### Tamagui Version

```markdown
^1.88.19 and above all
```

### Platform (Web, iOS, Android)

```markdown
Web (Windows)
```

### Reproduction

```markdown
When using the command "npm create tamagui@latest --template expo-router" to create a standard Expo start, the Expo web does not start up at all.

npm create tamagui@latest --template expo-router
cd expo-router
yarn install
yarn start
press w

And, the terminal freezes, and you can no longer perform any actions!
```

### System Info

```markdown
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 7.30 GB / 15.91 GB
  Binaries:
    Node: 18.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.23.9 
    @expo/vector-icons: ^14.0.0 => 14.0.0
    @react-navigation/native: ^6.0.2 => 6.1.9
    @tamagui/config: ^1.88.19 => 1.88.19
    @tamagui/metro-plugin: ^1.88.19 => 1.88.19
    @types/react: ~18.2.45 => 18.2.51
    expo: ~50.0.5 => 50.0.5
    expo-font: ~11.10.2 => 11.10.2
    expo-linking: ~6.2.2 => 6.2.2
    expo-router: ~3.4.6 => 3.4.6
    expo-splash-screen: ~0.26.4 => 0.26.4
    expo-status-bar: ~1.11.1 => 1.11.1
    expo-system-ui: ~2.9.3 => 2.9.3
    expo-web-browser: ~12.8.2 => 12.8.2
    jest: ^29.2.1 => 29.7.0
    jest-expo: ~50.0.1 => 50.0.1
    react: 18.2.0 => 18.2.0
    react-dom: 18.2.0 => 18.2.0
    react-native: 0.73.2 => 0.73.2
    react-native-safe-area-context: 4.8.2 => 4.8.2
    react-native-screens: ~3.29.0 => 3.29.0
    react-native-web: ~0.19.6 => 0.19.10
    react-test-renderer: 18.2.0 => 18.2.0
    tamagui: ^1.88.19 => 1.88.19
    typescript: ^5.1.3 => 5.3.3
```

**Comment by Naruto1200** [comment]
I also get this when adding Tamagui to expo router. When loading WEB it gets stuck and ensures that Android & IOS no longer work either (when removing Tamagui it works just fine)

**Comment by TheEhsanSarshar** [comment]
is this a windows only issue ? I have just tested it and it's working fine

**Comment by jersoncarin** [comment]
this is what i face right now, it stuck, I hope they will fix this.

**Comment by Jheysson** [comment]
Same thing here. It just happened for `--web` but now it's happening for `start` only without the `--web`. I'm also using tamagui

**Comment by Naruto1200** [comment]
I tried to run it on linux  (using WSL2) and the web version worked just fine. It no longer got stuck on loading and i started getting errors about google auth (which means that it worked)

So i think that Web for expo + tamagui just isn't supported on Windows anymore :(

**Comment by Jheysson** [comment]
@Naruto1200 You are right, it works fine in WSL
To be able to scan the QR when you start the app, you need the following command:
`npm start -- --tunnel`
I will ask you to install a package before staring

**Comment by CrownFist** [comment]
Also experiencing this same issue on Windows 11. Fresh install, gets stuck on web.

**Comment by TheEhsanSarshar** [comment]
I pushed a fixed for windows, please try it with latest version of Tamagui

**Comment by natew** [comment]
lmk if still an issue please

**Comment by kamaldeepj** [comment]
I am still facing this issue when creating an app with Expo Router and setting up tamagui
