### ISSUE TITLE
`AlertDialog` non-functional on native

### ISSUE THREAD

**Issue by wongk** [tamagui/tamagui#2798]
### Current Behavior

`AlertDialog` no longer opens on native. This is a regression. When the trigger is pressed, nothing happens. It works fine on web.

### Tamagui Version

```markdown
1.102.1
```

### Platform (Web, iOS, Android)

```markdown
iOS, Android
```

### Reproduction

```markdown
<AlertDialog>
      <AlertDialog.Trigger>{trigger}</AlertDialog.Trigger>
      <AlertDialog.Portal>
        <AlertDialog.Overlay
          key="overlay"
          animation="quick"
          opacity={0.5}
          enterStyle={{ opacity: 0 }}
          exitStyle={{ opacity: 0 }}
        />
        <AlertDialog.Content
          bordered
          elevate
          key="content"
          animation={[
            "quick",
            {
              opacity: {
                overshootClamping: true,
              },
            },
          ]}
          enterStyle={{ x: 0, y: -20, opacity: 0, scale: 0.9 }}
          exitStyle={{ x: 0, y: 10, opacity: 0, scale: 0.95 }}
          x={0}
          scale={1}
          opacity={1}
          y={0}
        >
          <YStack>
            <AlertDialog.Title>{title}</AlertDialog.Title>
            <AlertDialog.Description>
              <Text>{`Are you sure you want to ${content}?`}</Text>
            </AlertDialog.Description>
            <XStack gap="$3" justifyContent="flex-end">
              <AlertDialog.Cancel asChild>
                <Button variant="containedSecondary">Cancel</Button>
              </AlertDialog.Cancel>
              <AlertDialog.Action asChild>
                <Button variant="containedPrimary" onPress={onConfirm}>
                  Confirm
                </Button>
              </AlertDialog.Action>
            </XStack>
          </YStack>
        </AlertDialog.Content>
      </AlertDialog.Portal>
    </AlertDialog>
```
```


### System Info

_No response_

**Comment by CatStudioApp** [comment]
I'm seeing the same issue...
even using PortalProvider, it does not work.

The whole app sometimes feels freezed btw

**Comment by wongk** [comment]
I am able to get the dialog to display when using the `open` attribute directly. So this issue appears to be related to using the trigger element (we are using a Button).

As a workaround you can manipulate the `open` state "manually".

**Comment by wongk** [comment]
This happens when the `asChild` attribute is omitted from the `AlertDialog.Trigger` element.

**Comment by natew** [comment]
So must be something like it's not propagating the press from the inner to outer component?

**Comment by agrittiwari** [comment]
@natew Facing the same issue, you mentioned. the onPress inside the Alert portal is not listening the trigger `handlePressAccept` inside `AlertDialog.Action` when native prop is true. This issue relates to an [existing issue](https://github.com/tamagui/tamagui/issues/1852)
```
<AlertDialog.Action asChild>
                <Button backgroundColor={'$primary'} onPress={ handlePressAccept}>
                  {acceptLabel}
                </Button>
              </AlertDialog.Action>
```
https://github.com/user-attachments/assets/ca4bfdb1-9aec-4d79-bbba-96a1fdbe31bd

**Comment by christian1koch** [comment]
@agrittiwari I have the exact same issue.

**Comment by dieguezguille** [comment]
i am also having issues with the `AlertDialog` on native with tamagui `1.116.1`. web version works as expected but on native the dialog opens inside the component instead of being displayed full screen as it does on web

**Comment by chakrihacker** [comment]
@dieguezguille  Are you using new arch and react native 0.76??

**Comment by benjipott** [comment]
@agrittiwari to fix move on press directly on handler
```
<AlertDialog.Action asChild onPress={ handlePressAccept}>
  <Button backgroundColor={'$primary'} >
    {acceptLabel}
  </Button>
</AlertDialog.Action>
```

**Comment by thoughtspeed7** [comment]
I upgraded to Expo SDK 52, React Native 0.76.3 and Tamagui 1.120.1. AlertDialog works on iOS but not on Android. Even with the portal provider. Any solution?

**Comment by natew** [comment]
can you check latest release? we fixed dialogs

**Comment by bangdy** [comment]
need help! 
version is 1.125.31 , android still not working in Dialog

**Comment by Ammar1999y** [comment]
I tested it on version `1.125.26`, and it worked fine. However, after updating to any newer version, it stopped working. Also, all Tamagui-related packages should be on the same version.
```
import { Button, Pressable, Text, View } from "react-native";
import { AlertDialog } from "tamagui";
import { createTamagui, TamaguiProvider } from "tamagui";
import { config } from "@tamagui/config/v3";
const tamaguiConfig = createTamagui(config);
export default function Page() {
  return (
    <TamaguiProvider config={tamaguiConfig}>
      <AlertDialog native={false} open={true}>
        <AlertDialog.Trigger asChild>
          <Button title="Show Alert" />
        </AlertDialog.Trigger>

        <AlertDialog.Portal>
          <AlertDialog.Overlay
            key="overlay"
            animation="quick"
            opacity={0.5}
            enterStyle={{ opacity: 0 }}
            exitStyle={{ opacity: 0 }}
          />
          <AlertDialog.Content
            bordered
            elevate
            key="content"
            animation={[
              "quick",
              {
                opacity: {
                  overshootClamping: true,
                },
              },
            ]}
            enterStyle={{ x: 0, y: -20, opacity: 0, scale: 0.9 }}
            exitStyle={{ x: 0, y: 10, opacity: 0, scale: 0.95 }}
            x={0}
            scale={1}
            opacity={1}
            y={0}
          >
            <View>
              <AlertDialog.Title>Accept</AlertDialog.Title>
              <AlertDialog.Description>
                By pressing yes, you accept our terms and conditions.
              </AlertDialog.Description>

              <View>
                <AlertDialog.Action asChild>
                  <Pressable>
                    <Text>Accept</Text>
                  </Pressable>
                </AlertDialog.Action>
              </View>
            </View>
          </AlertDialog.Content>
        </AlertDialog.Portal>
      </AlertDialog>
    </TamaguiProvider>
  );
}

**Comment by anhquan291** [comment]
Tested one latest tamagui version and it works. 
Closing it now. If you still see any issues, feel free to reopen! Thanks guys

https://github.com/user-attachments/assets/64ae40fc-d6a7-4bcc-918d-eb6ec4f9b125
