### ISSUE TITLE
[bug] vite + ts + tamagui project cannot be started

### ISSUE THREAD

**Issue by bureyburey** [tamagui/tamagui#291]
## **Description**
Heya, let me start by saying nice work on this repo, it's coming along very nicely :)

Now let's get down to it...

I've encountered the following issue while attempting to run Tamagui in a Vite + TS application that uses .tsx files.

This is the error message that appears when opening the app (it only appears when the app is first opened)
![image](https://user-images.githubusercontent.com/20264976/196882231-039e359b-72e6-4f1d-a0af-2a2d7dcf819e.png)
and this is the the entire error output when running `yarn dev` and opening the app (the error occurs after opening):

```
vite-ts-tamagui on  main [⇡!] is 📦 v0.0.0 via ⬢ v14.20.0 
➜ yarn dev
yarn run v1.22.19
$ TAMAGUI_TARGET=web vite
Port 5173 is in use, trying another one...
Port 5174 is in use, trying another one...
Port 5175 is in use, trying another one...

  VITE v3.1.8  ready in 623 ms

  ➜  Local:   http://127.0.0.1:5176/
  ➜  Network: use --host to expose

Tamagui built config and components:

  - Config: ./dist/tamagui-node/tamagui.config.js
  - Components: ./dist/tamagui-node/tamagui-components.config.js

Tamagui failed requiring /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui.config.js from your tamagui.config.ts file, ignoring
 Must use import to load ES Module: /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui.config.js
require() of ES modules is not supported.
require() of /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui.config.js from /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename tamagui.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bgalili/projects/vite-ts-tamagui/package.json.
 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui.config.js
require() of ES modules is not supported.
require() of /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui.config.js from /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename tamagui.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bgalili/projects/vite-ts-tamagui/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at Module.require (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/require.js:62:22)
    at require (internal/modules/cjs/helpers.js:101:18)
    at loadTamagui (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:101:18)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.load [as loadTamagui] (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/createExtractor.js:84:42)
Tamagui error bundling components Must use import to load ES Module: /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui-components.config.js
require() of ES modules is not supported.
require() of /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui-components.config.js from /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename tamagui-components.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bgalili/projects/vite-ts-tamagui/package.json.
 Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui-components.config.js
require() of ES modules is not supported.
require() of /Users/bgalili/projects/vite-ts-tamagui/dist/tamagui-node/tamagui-components.config.js from /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename tamagui-components.config.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bgalili/projects/vite-ts-tamagui/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:281:35
    at Array.map (<anonymous>)
    at loadComponents (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:280:47)
    at loadTamagui (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:104:8)
10:28:42 AM [vite] Internal server error: Cannot read property 'length' of undefined
  Plugin: tamagui-extract
  File: /Users/bgalili/projects/vite-ts-tamagui/src/main.tsx
      at simpleHash3 (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/core-node/dist/static.js:431:23)
      at createCSSVariable (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/core-node/dist/static.js:9362:46)
      at variableToCSS (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/core-node/dist/static.js:12929:15)
      at /Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/core-node/dist/static.js:13179:29
      at createTamagui (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/core-node/dist/static.js:13245:5)
      at loadTamagui (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/loadTamagui.js:118:38)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.load [as loadTamagui] (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/createExtractor.js:84:42)
      at async extractToClassNames (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/static/dist/extractor/extractToClassNames.js:68:3)
      at async TransformContext.transform (/Users/bgalili/projects/vite-ts-tamagui/node_modules/@tamagui/vite-plugin/dist/cjs/extract.js:149:25)
```

at this point the error message from the image above appears on the browser.

a refresh would result in the additional error and the termination of the app:
```
Missing theme, an error occurred when importing your config
Got themes: [Function (anonymous)] {
  displayName: 'ProxyWorm - Check excludeReactNativeWebExports',
  _isProxyWorm: true
}
Looking for theme: displayName
✨  Done in 70.20s.

vite-ts-tamagui on  main [⇡!] is 📦 v0.0.0 via ⬢ v14.20.0 took 1m 10s 
➜ 
```

## **To Reproduce**
I've created the following [repo](https://github.com/bureyburey/vite-ts-tamagui-test)
and created an example that do work by rendering `/src/mainJSX.jsx` instead of `/src/main.tsx` (change commented lines inside the `index.html` file)

It seems that an attempt to render any file that ends with a .tsx extension would result in this error.
Additionally, the following files are generated (they are not generated when running `mainJSX.jsx`)

```
dist
  tamagui-node
    tamagui.config.js
    tamagui-components.config.js
```

The project was initialized using the `yarn create vite vite-ts-tamagui --template react-ts` command.

## **System Info**

Output of `npx envinfo --system --npmPackages --binaries --browsers`
```
➜ npx envinfo --system --npmPackages --binaries --browsers
npx: installed 1 in 1.038s

  System:
    OS: macOS 12.6
    CPU: (10) x64 Apple M1 Pro
    Memory: 44.40 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.20.0/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0
  npmPackages:
    @tamagui/config-base: ^1.0.1-beta.193 => 1.0.1-beta.193 
    @tamagui/shorthands: ^1.0.1-beta.193 => 1.0.1-beta.193 
    @tamagui/theme-base: ^1.0.1-beta.193 => 1.0.1-beta.193 
    @tamagui/vite-plugin: ^1.0.1-beta.193 => 1.0.1-beta.193 
    @types/react: ^18.0.17 => 18.0.21 
    @types/react-dom: ^18.0.6 => 18.0.6 
    @vitejs/plugin-react: ^2.1.0 => 2.1.0 
    react: ^18.2.0 => 18.2.0 
    react-dom: ^18.2.0 => 18.2.0 
    react-native-web: ^0.18.9 => 0.18.9 
    tamagui: ^1.0.1-beta.193 => 1.0.1-beta.193 
    typescript: ^4.6.4 => 4.8.4 
    vite: ^3.1.0 => 3.1.8 
```

**Comment by bureyburey** [comment]
## Update

when removing `tamaguiExtractPlugin(tamaguiConfig)` from `vite.config.ts` these errors are gone but i am getting a new error in a `.ts` file I have (updated repo, see `/src/Storage.ts`):
![image](https://user-images.githubusercontent.com/20264976/196928653-9760d6ab-d817-486a-8cb8-1eef1af7fabd.png)

For some reason `.ts` files are regarded as `.tsx` files, causing this error to be thrown.

**Comment by natew** [comment]
Fixed in 8071c146cb18698e77129ba31e62cddd2ecde00c

**Comment by bureyburey** [comment]
great :)

I am able to add the `tamaguiPlugin` to vite plugins array now and use .tsx files

still having an `Invalid export from package path/to/project/.tamagui/tamagui-node/tamagui-components.config.js` issue when adding the `tamaguiExtractPlugin` but for now it's not really a blocker for me.

**Comment by alburdette619** [comment]
I'm still having this issue currently with a `vite@latest` build. I put in the production flag as suggested so `build` fails but `dev` works...
