### ISSUE TITLE
`createCheckbox` throws `React does not recognize the scaleIcon prop on a DOM element`

### ISSUE THREAD

**Issue by guillempuche** [tamagui/tamagui#2935]
### Current Behavior

The horizontal checkboxes in https://tamagui.dev/bento/forms/checkboxes works, but it produces a React error. It's because `createCheckboxe` from `@tamagui/checkbox`.

The error is produced in these lines https://github.com/guillempuche/test-tamagui-checkboxes/blob/cc1af9cae6a428e06a5bc5374239385a9e0564ed/packages/app/features/home/horizontal_checkboxes.tsx#L94-L100

### Expected Behavior

Checkboxes is clean of warnings

### Tamagui Version

```markdown
1.111.11
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
1. Clone this repo https://github.com/guillempuche/test-tamagui-checkboxes
2. `yarn install`
3. `yarn web`
4. Open http://localhost:3000/
5. Open browser's console and get the error
```

### System Info

```markdown
System:
    OS: macOS 14.7
    CPU: (8) arm64 Apple M1
    Memory: 76.52 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 4.5.0 - ~/.nvm/versions/node/v20.14.0/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
    bun: 1.1.17 - ~/.nvm/versions/node/v20.14.0/bin/bun
    Watchman: 2024.08.12.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 128.1.69.162
    Chrome: 128.0.6613.139
    Safari: 17.6
  npmPackages:
    @babel/runtime: ^7.24.6 => 7.24.6 
    @manypkg/cli: ^0.21.4 => 0.21.4 
    check-dependency-version-consistency: ^4.1.0 => 4.1.0 
    eslint: ^9.3.0 => 9.4.0 
    node-gyp: ^10.1.0 => 10.1.0 
    prettier: ^3.3.3 => 3.3.3 
    turbo: ^1.13.4 => 1.13.4 
    typescript: ^5.6.2 => 5.6.2 
    vitest: ^2.1.1 => 2.1.1
```

**Comment by sensor** [comment]
This needs some attention. I just updated my tamagui packages and every Checkpoint component throws this warning.

**Comment by guillempuche** [comment]
It could come from:

```ts
const Checkbox = TCheckbox.styleable((props, ref) => {
  const { checked: userChecked, onCheckedChange, ...rest } = props
  const { values, onValuesChange } = CheckboxesContext.useStyledContext()
  const { value: focusItemValue } = FocusItemContext.useStyledContext()

  const attrs = {
    checked: values[focusItemValue],
    onCheckedChange: (checked: CheckedState) => {
      onValuesChange({
        ...values,
        [focusItemValue]:
          typeof checked === 'boolean' ? checked : !values[focusItemValue],
      })
    },
    ...rest,
  }

  return <TCheckbox ref={ref} value={focusItemValue} {...rest} {...attrs} /> // <---- Here
})
```

**Comment by natew** [comment]
This should be fixed lmk if not

**Comment by guillempuche** [comment]
@natew, I still get the error

<img width="448" alt="image" src="https://github.com/user-attachments/assets/976d5873-1f24-484c-be86-622eb3be0045">

```tsx
/**
 * Copied from Tamagui Bento
 */

import type { KeyboardEvent, PropsWithChildren, Ref } from 'react'
import { forwardRef } from 'react'

import {
	Group,
	Label,
	RovingFocusGroup,
	type RovingFocusGroupProps,
	type RovingFocusItemProps,
	Checkbox as TamaguiCheckbox,
	type TamaguiCheckedState,
	type TamaguiGetProps,
	View,
	type YStackProps,
	createStyledContext,
	isWeb,
	styled,
	withStaticProperties,
} from '@xiroi/shared-ui-core'
import { zIndices } from '@xiroi/shared-ui-core/themes'
import { CoText } from './co_text'

export const CheckboxesContext = createStyledContext<{
	values: Record<string, boolean>
	onValuesChange: (values: Record<string, boolean>) => void
}>({
	values: {},
	onValuesChange: () => {},
})

const FocusGroup = forwardRef<
	React.ElementRef<typeof View>,
	RovingFocusGroupProps
>((props, ref) => {
	return (
		<RovingFocusGroup
			focusable
			outlineOffset={1}
			focusStyle={{
				zIndex: zIndices.dropdown,
			}}
			{...props}
			ref={ref}
		/>
	)
})

const FocusItemContext = createStyledContext({
	value: '',
})

const FocusGroupItem = forwardRef<
	any,
	RovingFocusItemProps & { value: string }
>((props, ref) => {
	const { value, ...rest } = props
	const { values, onValuesChange } = CheckboxesContext.useStyledContext()

	const attrs = {
		focusable: true,
		outlineOffset: 1,
		flexShrink: 1,
		focusStyle: {
			zIndex: zIndices.default,
		},
		...(isWeb && {
			onKeyDown: (e: KeyboardEvent) => {
				if (e.target !== e.currentTarget) return
				if (e.key === 'Enter' || e.code === 'Space') {
					onValuesChange({ ...values, [value]: !values[value] })
				}
			},
		}),
		onPress: () => {
			onValuesChange({ ...values, [value]: !values[value] })
		},
		...rest,
	}

	return (
		<FocusItemContext.Provider value={value}>
			<RovingFocusGroup.Item ref={ref} {...attrs} />
		</FocusItemContext.Provider>
	)
})

const CheckboxGroup = styled(Group, {
	name: 'CoCheckboxGroup',

	orientation: 'vertical',
})

const Header = styled(CoText, {
	name: 'CoCheckboxHeader',
})

const CheckboxesImp = <K extends string>(
	props: PropsWithChildren<CheckboxesProps<K>>,
) => {
	const { values, onValuesChange, ...rest } = props

	return (
		<CheckboxesContext.Provider values={values} onValuesChange={onValuesChange}>
			<View {...rest} />
		</CheckboxesContext.Provider>
	)
}
type CheckboxesProps<K extends string> = {
	values: Record<K, boolean>
	onValuesChange: (values: Record<K, boolean>) => void
} & YStackProps

const Checkbox = TamaguiCheckbox.styleable(
	(props: CheckboxProps, ref: Ref<any>) => {
		const {
			scaleIcon, // Extracted to prevent passing to DOM. React does not recognize it.
			checked: userChecked,
			children,
			onCheckedChange,
			...rest
		} = props
		const { values, onValuesChange } = CheckboxesContext.useStyledContext()
		const { value: focusItemValue } = FocusItemContext.useStyledContext()

		const attrs = {
			checked: values[focusItemValue] ?? false,
			onCheckedChange: (checked: TamaguiCheckedState) => {
				onValuesChange({
					...values,
					[focusItemValue]:
						typeof checked === 'boolean' ? checked : !values[focusItemValue],
				})
			},
			...rest,
		}

		return (
			<TamaguiCheckbox ref={ref} value={focusItemValue} {...rest} {...attrs}>
				{children}
			</TamaguiCheckbox>
		)
	},
)
type CheckboxProps = TamaguiGetProps<typeof TamaguiCheckbox>

const CardFrame = styled(View, {
	name: 'CoCardFrame',

	cursor: 'pointer',
	width: '100%',
	borderRadius: '$roundedMd',
	padding: '$spacingSm',
	backgroundColor: '$surfaceContainerLow',
	borderColor: '$outlineVariant',
	borderWidth: 2,
	focusStyle: {
		backgroundColor: '$surfaceContainerHigh',
		borderColor: '$primary',
	},
	hoverStyle: {
		backgroundColor: '$surfaceContainerHigh',
		borderColor: '$outlineVariant',
	},

	...(process.env.TAMAGUI_TARGET === 'web' && {
		pressStyle: {
			backgroundColor: '$surfaceContainerHighest',
			borderColor: '$primary',
		},
	}),

	variants: {
		active: {
			true: {
				backgroundColor: '$surfaceContainerHigh',
				borderColor: '$primary',
			},
		},
	} as const,
})

const Card = CardFrame.styleable((props: CardProps, ref: Ref<any>) => {
	const { children, ...rest } = props
	const { values } = CheckboxesContext.useStyledContext()
	const { value } = FocusItemContext.useStyledContext()
	const isSelected = values[value]

	return (
		<CardFrame ref={ref} {...rest} active={isSelected}>
			{children}
		</CardFrame>
	)
})
type CardProps = TamaguiGetProps<typeof CardFrame>

export const CoCheckboxes = withStaticProperties(CheckboxesImp, {
	Group: withStaticProperties(CheckboxGroup, {
		Item: Group.Item,
	}),
	Header,
	FocusGroup: withStaticProperties(FocusGroup, {
		Item: FocusGroupItem,
	}),
	Checkbox: withStaticProperties(Checkbox, {
		Indicator: TamaguiCheckbox.Indicator,
		Label,
	}),
	Card,
})
```

**Comment by wkoutre** [comment]
@natew i don't think this is fixed, i'm still receiving the error in 1.122.7 from Checkbox when running a unit test suite with Jest

```
 at ../../node_modules/@tamagui/animations-moti/dist/cjs/createAnimations.cjs:47:11
      at AnimatedComponent (../../node_modules/react-native-reanimated/lib/module/createAnimatedComponent/createAnimatedComponent.js:72:7)
      at Provider (../../node_modules/@tamagui/web/dist/cjs/helpers/createStyledContext.cjs:50:7)
      at ../../node_modules/@tamagui/web/dist/cjs/createComponent.cjs:144:155
      at Provider (../../node_modules/@tamagui/web/dist/cjs/helpers/createStyledContext.cjs:50:7)
      at ../../node_modules/@tamagui/checkbox/dist/cjs/createCheckbox.cjs:65:11
      at ../../node_modules/@tamagui/web/dist/cjs/views/Theme.cjs:47:3
      at Provider (../../node_modules/@tamagui/web/dist/cjs/helpers/createStyledContext.cjs:50:7)
      at ../../node_modules/@tamagui/web/dist/cjs/helpers/themeable.cjs:45:7
          at div
      at ../../node_modules/@tamagui/web/dist/cjs/createComponent.cjs:144:155
      at checked (../../packages/ui/src/components/checkbox/Checkbox.tsx:55:28)
          at div
      at I (../../node_modules/styled-components/dist/styled-components.cjs.js:1:19113)
      at order (src/components/AccountDrawer/MiniPortfolio/Limits/LimitDetailActivityRow.tsx:48:42)
      at PortalProviderComponent (../../node_modules/@tamagui/portal/dist/cjs/GorhomPortal.cjs:134:5)
          at span
          at span
      at ../../node_modules/@tamagui/web/dist/cjs/views/Theme.cjs:47:3
      at ThemeProvider (../../node_modules/@tamagui/web/dist/cjs/views/ThemeProvider.cjs:50:11)
      at Provider (../../node_modules/@tamagui/web/dist/cjs/helpers/createStyledContext.cjs:50:7)
          at span
      at UnmountedClassName (../../node_modules/@tamagui/web/dist/cjs/views/TamaguiProvider.cjs:81:54)
      at TamaguiProvider (../../node_modules/@tamagui/web/dist/cjs/views/TamaguiProvider.cjs:44:3)
      at TamaguiProvider (../../node_modules/tamagui/dist/cjs/views/TamaguiProvider.cjs:30:3)
      at children (src/theme/tamaguiProvider.tsx:5:35)
```

**Comment by enghseb** [comment]
Same problem here. As soon as I use the Checkbox component.

**Comment by dohomi** [comment]
@natew the issue is still there. This also happens in many Bento components, for example inputParts or data table. 

The main reason behind this is that any context created by `createStyledContext` needs to be handled by styled components. I have seen many code fragments where empty `scaleIcon:()=>({})` blocks been defined to suppress the warning. In more complex components like data table it feels quite cumbersome to always handle `cellHeight` or `cellWidth` on components which does not support that variable.

**Comment by natew** [comment]
This issue appears to be fixed in the current codebase. I wrote tests to verify that `scaleIcon` does not leak to the DOM:

1. The standard `Checkbox` component correctly filters out `scaleIcon`
2. Custom checkboxes created with `createCheckbox()` also correctly filter it

The fix is in `createCheckbox.tsx` - `scaleIcon` is properly destructured from props at the HOC level (line 100) and only passed to `CheckboxStyledContext.Provider`, not spread onto the Frame component.

If you're still experiencing this issue, please provide a minimal reproduction case.
