### ISSUE TITLE
Sheets dont get displayed when used within Dialog with Adapt

### ISSUE THREAD

**Issue by samuba** [tamagui/tamagui#2979]
### Current Behavior

This bug was introduced in 1.114 it was not present in 1.113.
The Adapt does not seem to do anything anymore.

### Expected Behavior

It should work like in previous version

### Tamagui Version

```markdown
1.114
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
https://codesandbox.io/p/devbox/cocky-lederberg-hsy6gw?workspaceId=7d090568-57c5-4e26-b557-2174f275fdea

see: /packages/app/features/home/screen.tsx
```

**Comment by natew** [comment]
It says that sandbox is not found. But I'm seeing Adapt work on both the tamagui site and in our kitchen sink app on native.

**Comment by samuba** [comment]
Maybe we are using it wrong then, would love to get your opinion on it. It seems to be broken in multiple usages in our app.
The codesandbox should be available now, sorry for that https://codesandbox.io/p/devbox/cocky-lederberg-hsy6gw?workspaceId=7d090568-57c5-4e26-b557-2174f275fdea

**Comment by obonakdar2** [comment]
I have same problem, tamagui version 1.113.1

**Comment by natew** [comment]
fix coming out, sorry about that. we need to add a test @jonsherrard

**Comment by natew** [comment]
this should be fixed in new version i tested pretty thoroughly, lmk if no we can re-open

**Comment by skyriverbend** [comment]
@natew hmm I am still getting this issue on 1.116.2. Had to revert to canary (1.112.25-1728365940312) to fix it.

Unless there was some sort of breaking change and the way to use it has changed slightly...

**Comment by natew** [comment]
Ah sorry our tests only tested with platform included - fix going out now and adding a test case. Actually adding a much better test setup now in general so we can add these more easily.
