### ISSUE TITLE
Button background not respecting theme light/dark since v1.114.3 

### ISSUE THREAD

**Issue by seanadkinson** [tamagui/tamagui#3014]
### Current Behavior

Button background isn't updating with theme light/dark/inverse.  It stays light gray, unless a colored theme is used.

### Expected Behavior

Background is black for theme "dark", and light gray for theme "light"

### Tamagui Version

```markdown
Started in 1.114.3, behaving properly in 1.114.2
```

### Platform (Web, iOS, Android)

```markdown
Using iOS builds to see behavior.
```

### Reproduction

* Install starter app and select expo-router template (likely the template isn't important, but this is what I was testing with)
* Update `CurrentToast.tsx` with the following buttons:
```
                <Theme inverse>
                    <Button>
                        inverse
                    </Button>
                </Theme>
                <Theme name="light">
                    <Button>
                        light
                    </Button>
                </Theme>
                <Theme name="dark">
                    <Button>
                        dark
                    </Button>
                </Theme>
                <Theme name="red">
                    <Button>
                        red
                    </Button>
                </Theme>
```
* Run app, and notice that three out of four buttons are the same:

### System Info

```markdown
System:
    OS: macOS 14.6.1
    CPU: (16) arm64 Apple M3 Max
    Memory: 6.43 GB / 128.00 GB
    Shell: 3.7.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 22.9.0 - ~/.nvm/versions/node/v22.9.0/bin/node
    Yarn: 4.5.0 - ~/.nvm/versions/node/v22.9.0/bin/yarn
    npm: 10.8.3 - ~/.nvm/versions/node/v22.9.0/bin/npm
  Browsers:
    Chrome: 129.0.6668.101
    Chrome Canary: 132.0.6789.0
    Safari: 18.0.1
  npmPackages:
    @babel/core: ^7.24.6 => 7.25.2
    @expo/metro-config: ~0.18.4 => 0.18.11
    @expo/metro-runtime: ~3.2.1 => 3.2.3
    @react-navigation/native: ^6.1.17 => 6.1.18
    @tamagui/babel-plugin: ^1.115.5 => 1.115.5
    @tamagui/cli: ^1.115.5 => 1.115.5
    @tamagui/config: ^1.115.5 => 1.115.5
    @tamagui/lucide-icons: ^1.115.5 => 1.115.5
    @tamagui/metro-plugin: ^1.115.5 => 1.115.5
    @tamagui/toast: ^1.115.5 => 1.115.5
    @types/react: ~18.2.79 => 18.2.79
    @types/react-native: ^0.73.0 => 0.73.0
    babel-preset-expo: ^11.0.6 => 11.0.14
    burnt: ^0.12.2 => 0.12.2
    expo: ~51.0.32 => 51.0.32
    expo-build-properties: ~0.12.5 => 0.12.5
    expo-font: ~12.0.10 => 12.0.10
    expo-linking: ~6.3.1 => 6.3.1
    expo-router: ~3.5.23 => 3.5.23
    expo-splash-screen: ~0.27.5 => 0.27.5
    expo-status-bar: ^1.12.1 => 1.12.1
    expo-system-ui: ~3.0.7 => 3.0.7
    expo-web-browser: ~13.0.3 => 13.0.3
    react: 18.3.1 => 18.3.1
    react-dom: 18.3.1 => 18.3.1
    react-native: 0.75.2 => 0.75.2
    react-native-reanimated: ~3.15.1 => 3.15.1
    react-native-safe-area-context: 4.10.9 => 4.10.9
    react-native-screens: ~3.34.0 => 3.34.0
    react-native-svg: 15.6.0 => 15.6.0
    react-native-web: ^0.19.12 => 0.19.12
    tamagui: ^1.115.5 => 1.115.5
    typescript: ^5.5.2 => 5.6.2
```

**Comment by seanadkinson** [comment]
Screenshot of latest v 1.115.5:

<img width="364" alt="Screenshot 2024-10-21 at 1 07 17 PM" src="https://github.com/user-attachments/assets/cbd196c2-519c-4d5e-9dfe-3992847e15a3">

Screenshot of v 1.114.3:

<img width="364" alt="Screenshot 2024-10-21 at 1 09 20 PM" src="https://github.com/user-attachments/assets/ba3f42d8-3d24-4f9e-b2df-d710b74575a9">

Screenshot of v 1.114.2:

<img width="364" alt="Screenshot 2024-10-21 at 1 10 04 PM" src="https://github.com/user-attachments/assets/78afbddb-4d74-4a45-abe4-fcc0e2c4b679">

**Comment by jonsherrard** [comment]
Just tried this *outside* a Toast and it's working as expected. 

Potentially something to do with being nested in a Toast. Will check futher.

**Comment by seanadkinson** [comment]
@jonsherrard I was having this issue in my own app of course, and used the starter app to repro, but I wasn't using a Toast in my personal app when I saw this behavior.

Indeed though, even in the starter app, if I update `two.tsx` with the following, I still see the broken behavior:
```
export default function TabTwoScreen() {
  return (
    <View flex={1} alignItems="center" justifyContent="center" bg="$background">
      <Text fontSize={20} color="$blue10">
        Tab Two
      </Text>
        <Theme inverse>
            <Button>
                inverse
            </Button>
        </Theme>
        <Theme name="light">
            <Button>
                light
            </Button>
        </Theme>
        <Theme name="dark">
            <Button>
                dark
            </Button>
        </Theme>
        <Theme name="red">
            <Button>
                red
            </Button>
        </Theme>

    </View>
  )
}
```

Screenshot:
<img width="364" alt="Screenshot 2024-10-21 at 1 37 18 PM" src="https://github.com/user-attachments/assets/edadad7f-17eb-4782-9ee1-4e2af0421910">

So it doesn't feel like it has anything to do with `Toast`, but I could be wrong of course.

**Comment by natew** [comment]
Will take a look here shortly.

**Comment by natew** [comment]
i believe this was fixed, can re-open if not

**Comment by seanadkinson** [comment]
@natew This issue appears on the latest version, v1.115.5, so I think this issue should be reopened.  Here is the screenshot of Tab Two with the above changes:

<img width="368" alt="Screenshot 2024-10-21 at 9 16 56 PM" src="https://github.com/user-attachments/assets/083ba3ac-83b5-4c8c-a03a-62c1bc4d67fa">

**Comment by seanadkinson** [comment]
Just noticed that there is a new version available, v1.116.1.  I've confirmed the issue still appears on this latest version on iOS.  I also checked Android, which I hadn't in any of my previous reports, and this issue _does not_ appear on Android, so it may be an iOS-specific issue.

**Comment by boostvolt** [comment]
I can confirm `themeInverse` is not working in v1.116.8.

**Comment by natew** [comment]
Sorry guys, fix is out in 1.116.9 - though I think needs a further fix for deeply nested theme inverse which I have logged.

**Comment by natew** [comment]
It's going out now just closing so I can close tab :)
