### ISSUE TITLE
Bumping from 1.115.5 to 1.116.* causes @tamagui/use-did-finish-ssr to no longer resolve

### ISSUE THREAD

**Issue by anthonyn60** [tamagui/tamagui#3026]
### Current Behavior

Bumping past version 1.115.5 causes the `use-did-finish-ssr` module to no longer resolve. When adding the dependency manually, after app bootup I get the following: `TypeError: Cannot read property 'useState' of null`

### Expected Behavior

Upgrade the package version and it works as expected, or the module is added manually into `package.json` and the `useState` error does not occur.

### Tamagui Version

```markdown
1.116.0
```

### Platform (Web, iOS, Android)

```markdown
iOS, Android with Expo
```

### Reproduction

```markdown
I'm unable to reproduce on a starter repo but this is happening with both of the existing Tamagui/Expo codebases I'm working on.

The "unable to resolve" issue comes from `@tamagui/sheet/dist/cjs/createSheet.native.js` where `use-did-finish-ssr` is a dependency

The useState error after including it as a dependency is as follows:
TypeError: Cannot read property 'useState' of null

This error is located at:
    in UnmountedClassName
    in TamaguiProvider
    in TamaguiProvider
    in QueryClientProvider
    in SWRConfig
    in OrganizationProvider
    in ClerkContextProvider
```

![image](https://github.com/user-attachments/assets/9ae5627d-a016-40a8-8930-350c62c0fa41)

### System Info

```markdown
> envinfo --system --npmPackages --binaries --browsers


  System:
    OS: macOS 14.7
    CPU: (10) arm64 Apple M1 Pro
    Memory: 620.16 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 21.6.1 - ~/.nvm/versions/node/v21.6.1/bin/node
    Yarn: 4.0.2 - ~/.nvm/versions/node/v21.6.1/bin/yarn
    npm: 8.19.4 - ~/Documents/github/selflogistics/packmule-mobile/node_modules/.bin/npm
    bun: 1.1.20 - ~/.bun/bin/bun
    Watchman: 2024.01.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 130.0.6723.70
    Safari: 18.0
  npmPackages:
    @babel/core: ^7.25.2 => 7.25.2 
    @google/semantic-release-replace-plugin: 1.1.0 => 1.1.0 
    @graphql-codegen/cli: ^5.0.2 => 5.0.2 
    @graphql-codegen/introspection: ^4.0.3 => 4.0.3 
    @graphql-codegen/typescript-operations: ^4.2.3 => 4.2.3 
    @graphql-codegen/typescript-react-query: ^6.1.0 => 6.1.0 
    @manypkg/cli: ^0.21.4 => 0.21.4 
    @semantic-release/changelog: 6.0.1 => 6.0.1 
    @semantic-release/git: 10.0.1 => 10.0.1 
    @semantic-release/github: 8.0.6 => 8.0.6 
    @semantic-release/npm: 9.0.1 => 9.0.1 
    @semantic-release/release-notes-generator: 10.0.3 => 10.0.3 
    @sentry/react-native: ~5.24.3 => 5.24.3 
    @tamagui/animations-react-native: 1.116.0 => 1.116.0 
    @tamagui/babel-plugin: 1.116.0 => 1.116.0 
    @tamagui/config: 1.116.0 => 1.116.0 
    @tamagui/font-inter: 1.116.0 => 1.116.0 
    @tamagui/lucide-icons: 1.116.0 => 1.116.0 
    @tamagui/portal: 1.116.0 => 1.116.0 
    @tamagui/themes: 1.116.0 => 1.116.0 
    @tamagui/toast: 1.116.0 => 1.116.0 
    @tanstack/react-query: ^5.55.2 => 5.55.2 
    @types/react: ~18.2.79 => 18.2.79 
    @typescript-eslint/eslint-plugin: ^8.4.0 => 8.4.0 
    @typescript-eslint/parser: ^8.4.0 => 8.4.0 
    babel-plugin-module-resolver: ^5.0.2 => 5.0.2 
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4 
    burnt: ^0.12.2 => 0.12.2 
    conventional-changelog-conventionalcommits: ^8.0.0 => 8.0.0 
    eslint: ^9.10.0 => 9.10.0 
    eslint-config-prettier: ^9.1.0 => 9.1.0 
    eslint-plugin-prettier: ^5.2.1 => 5.2.1 
    eslint-plugin-react: ^7.35.2 => 7.35.2 
    eslint-plugin-simple-import-sort: ^12.1.1 => 12.1.1 
    expo: ~51.0.38 => 51.0.38 
    expo-build-properties: ~0.12.5 => 0.12.5 
    expo-camera: ~15.0.16 => 15.0.16 
    expo-constants: ~16.0.2 => 16.0.2 
    expo-doctor: ^1.10.1 => 1.10.1 
    expo-font: ~12.0.10 => 12.0.10 
    expo-haptics: ~13.0.1 => 13.0.1 
    expo-linear-gradient: ~13.0.2 => 13.0.2 
    expo-linking: ~6.3.1 => 6.3.1 
    expo-router: ~3.5.23 => 3.5.23 
    expo-secure-store: ~13.0.2 => 13.0.2 
    expo-splash-screen: ~0.27.6 => 0.27.6 
    expo-status-bar: ~1.12.1 => 1.12.1 
    expo-system-ui: ~3.0.7 => 3.0.7 
    expo-updates: ~0.25.27 => 0.25.27 
    graphql: ^16.8.2 => 16.9.0 
    prettier: ^3.3.3 => 3.3.3 
    react: 18.2.0 => 18.2.0 
    react-dom: 18.2.0 => 18.2.0 
    react-native: 0.74.5 => 0.74.5 
    react-native-gesture-handler: ~2.16.1 => 2.16.2 
    react-native-reanimated: ~3.10.1 => 3.10.1 
    react-native-safe-area-context: 4.10.5 => 4.10.5 
    react-native-screens: 3.31.1 => 3.31.1 
    react-native-svg: 15.2.0 => 15.2.0 
    react-native-svg-transformer: ^1.5.0 => 1.5.0 
    semantic-release: 19.0.5 => 19.0.5 
    tamagui: 1.116.0 => 1.116.0 
    typescript: ~5.3.3 => 5.3.3 
    zod: ^3.23.8 => 3.23.8
```

**Comment by natew** [comment]
Looking into it, have a fix going out for the missing dep but will try and replicate this somehow, I too can't seem to replicate in the starters/monorepo at all so I'll set up a new app

**Comment by natew** [comment]
Tried on a fresh expo app on both the new beta and the current latest, both are working with this example:

```
import { config as configIn } from '@tamagui/config/v3'
import { Check, ChevronDown, ChevronUp } from '@tamagui/lucide-icons'
import React from 'react'
import { SafeAreaView } from 'react-native-safe-area-context'
import {
  Adapt,
  type FontSizeTokens,
  Select,
  type SelectProps,
  Sheet,
  TamaguiProvider,
  YStack,
  createTamagui,
  getFontSize,
} from 'tamagui'

const config = createTamagui(configIn)

export function TestCase1() {
  return (
    <TamaguiProvider config={config} defaultTheme="light">
      <SafeAreaView>
        <Test />
      </SafeAreaView>
    </TamaguiProvider>
  )
}

function Test(props: SelectProps) {
  const [val, setVal] = React.useState('apple')

  return (
    <Select value={val} onValueChange={setVal} disablePreventBodyScroll {...props}>
      <Select.Trigger width={220} iconAfter={ChevronDown}>
        <Select.Value placeholder="Something" />
      </Select.Trigger>

      <Adapt when="sm" platform="touch">
        <Sheet
          native={!!props.native}
          modal
          dismissOnSnapToBottom
          animationConfig={{
            type: 'spring',
            damping: 20,
            mass: 1.2,
            stiffness: 250,
          }}
        >
          <Sheet.Frame>
            <Sheet.ScrollView>
              <Adapt.Contents />
            </Sheet.ScrollView>
          </Sheet.Frame>
          <Sheet.Overlay animation="quick" enterStyle={{ opacity: 0 }} exitStyle={{ opacity: 0 }} />
        </Sheet>
      </Adapt>

      <Select.Content zIndex={200000}>
        <Select.ScrollUpButton
          alignItems="center"
          justifyContent="center"
          position="relative"
          width="100%"
          height="$3"
        >
          <YStack zIndex={10}>
            <ChevronUp size={20} />
          </YStack>
        </Select.ScrollUpButton>

        <Select.Viewport
          // to do animations:
          // animation="quick"
          // animateOnly={['transform', 'opacity']}
          // enterStyle={{ o: 0, y: -10 }}
          // exitStyle={{ o: 0, y: 10 }}
          minWidth={200}
        >
          <Select.Group>
            <Select.Label>Fruits</Select.Label>
            {/* for longer lists memoizing these is useful */}
            {React.useMemo(
              () =>
                items.map((item, i) => {
                  return (
                    <Select.Item index={i} key={item.name} value={item.name.toLowerCase()}>
                      <Select.ItemText>{item.name}</Select.ItemText>
                      <Select.ItemIndicator marginLeft="auto">
                        <Check size={16} />
                      </Select.ItemIndicator>
                    </Select.Item>
                  )
                }),
              [items]
            )}
          </Select.Group>

          {/* Native gets an extra icon */}
          {props.native && (
            <YStack
              position="absolute"
              right={0}
              top={0}
              bottom={0}
              alignItems="center"
              justifyContent="center"
              width={'$4'}
              pointerEvents="none"
            >
              <ChevronDown size={getFontSize((props.size as FontSizeTokens) ?? '$true')} />
            </YStack>
          )}
        </Select.Viewport>

        <Select.ScrollDownButton
          alignItems="center"
          justifyContent="center"
          position="relative"
          width="100%"
          height="$3"
        >
          <YStack zIndex={10}>
            <ChevronDown size={20} />
          </YStack>
        </Select.ScrollDownButton>
      </Select.Content>
    </Select>
  )
}

const items = [
  { name: 'Apple' },
  { name: 'Pear' },
  { name: 'Blackberry' },
  { name: 'Peach' },
  { name: 'Apricot' },
  { name: 'Melon' },
  { name: 'Honeydew' },
  { name: 'Starfruit' },
  { name: 'Blueberry' },
  { name: 'Raspberry' },
  { name: 'Strawberry' },
  { name: 'Mango' },
  { name: 'Pineapple' },
  { name: 'Lime' },
  { name: 'Lemon' },
  { name: 'Coconut' },
  { name: 'Guava' },
  { name: 'Papaya' },
  { name: 'Orange' },
  { name: 'Grape' },
  { name: 'Jackfruit' },
  { name: 'Durian' },
]
```

**Comment by Pamavoc** [comment]
Same here with expo 52 & next inside a bun monorepo. It's using tamagui 1.116. I need to try later with React 18.3.1 and not React 18.2.0

**Comment by natew** [comment]
Fix just went out making react versioning looser, was suspecting maybe our range was causing issues so hopefully that helps. Will check that setup next.

**Comment by natew** [comment]
Made it looser - let me know if that helps guys.

**Comment by anthonyn60** [comment]
Can confirm that bumping to 18.3.1 solved my problem, with a caveat.

Expo (via `expo-doctor`) still recommends version 18.2.0, which results in two versions being installed.

```
yarn why react

├─ @tamagui/portal@npm:1.116.11
│  └─ react@npm:18.3.1 (via npm:>=18.0.0)
│
├─ @tamagui/react-native-web-internals@npm:1.116.11
│  └─ react@npm:18.3.1 (via npm:>=18.0.0)
│
├─ @tamagui/start-transition@npm:1.116.11
│  └─ react@npm:18.3.1 (via npm:>=18.0.0)
│
├─ @tamagui/web@npm:1.116.11
│  └─ react@npm:18.3.1 (via npm:>=18.0.0)
│
└─ app-title@workspace:.
   └─ react@npm:18.2.0 (via npm:18.2.0)
```

The workspace runs 18.2.0 while Tamagui runs 18.3.1. Not sure what that's all about.

**Comment by natew** [comment]
We don't depend on 18.2 or 18.3, either should work and either should install fine. Would be great to get a repo that reproduces this so I can see. But you may also just have had your old lockfile or something.

**Comment by natew** [comment]
Loosening the react-dom version in the release going out now - that maybe could've caused some issues.

**Comment by steflsd** [comment]
Using pnpm with expo 51. Still getting the same error.  Im using the packages as downgraded by expo-doctor to the supported expo 51 versions.  Delete pnpm-lock.yaml and regenerated. Same issue...

**Comment by natew** [comment]
@steflsd which error? We fixed the use-did-finish-ssr one I assume, so you're seeing the `TypeError: Cannot read property 'useState' of null`?

Just went through all our templates this morning and can't replicate still. Tried fixing react/react-dom to 18.2.0 and its working as well for me :/

Looking back at the 1.116 changes and can't see anything obvious. We upgraded `react-remove-scroll` but I don't see anything in that or the sub-dependencies.

Would really, really be helpful to have a reproduction, I've tried so many now.

**Comment by jsve** [comment]
I'm on 1.116.12 now. Still getting `TypeError: Cannot read properties of null (reading 'useState')` on react 18.2. Works on 18.3 (with this caveat: https://github.com/tamagui/tamagui/issues/3035).

**Comment by steflsd** [comment]
> @steflsd which error? We fixed the use-did-finish-ssr one I assume, so you're seeing the `TypeError: Cannot read property 'useState' of null`?
> 
> 
> 
> Just went through all our templates this morning and can't replicate still. Tried fixing react/react-dom to 18.2.0 and its working as well for me :/
> 
> 
> 
> Looking back at the 1.116 changes and can't see anything obvious. We upgraded `react-remove-scroll` but I don't see anything in that or the sub-dependencies.
> 
> 
> 
> Would really, really be helpful to have a reproduction, I've tried so many now.

Yeah. Usestate null. I understand how difficult these are to reproduce. Question to those with errors. 

Which package manager? pnpm (9) our side. I know some expo packages have resolution issues with pnpm sometimes.

**Comment by mphill** [comment]
This occurs with a stock install of `yarn create tamagui@latest --template expo-router` if you are looking for a repo @natew

**Comment by natew** [comment]
@mphill I just tried expo-router template and iOS + web are both working for me, this is so odd....

**Comment by natew** [comment]
Oh I can see - if I downgrade to 18.2 it does keep it... wtf? This must be a semver bug in yarn or something. Checking a few things, I may just say fuck it and set react/react-dom to `*` though this is insane.

**Comment by natew** [comment]
Release going out - I'm giving up on react versioning, even in local testing it's hard for me to get yarn to behave even if I removed the react and react-dom entirely from the package.json and cleared yarn.lock. I think it's relatively safe to just have it `*` anyway, and not worth all the effort of me trying to figure out what's going on here.

**Comment by anthonyn60** [comment]
^This resolved it for me. Thank you @natew for looking into this and addressing it.
