### ISSUE TITLE
[bug] Style propagation issues with yarn web:prod

### ISSUE THREAD

**Issue by GigaBigBoss** [tamagui/tamagui#321]
**Describe the bug**
Happening on version 199 + 200 and older versions.
Using the following component with the Next starter with JSX enabled placed within the main homescreen function I'm getting differences in styling when using yarn web:prod as opposed to yarn web.
![image](https://user-images.githubusercontent.com/106954969/199219392-47097e93-3abe-4a65-b1e6-f00b3a64dd84.png)

Yarn web
![chrome_BZIm6eRCWk](https://user-images.githubusercontent.com/106954969/199219686-32ed2acf-9b1e-4b2b-9530-a9ba137befbd.png)

yarn web:prod (Ignore contrast difference)
![mpc-hc64_75dnnJxZx2](https://user-images.githubusercontent.com/106954969/199219719-f4fa008e-3c24-4636-a484-6b4df3c6e4a2.png)

**To Reproduce**
https://github.com/GigaBigBoss/tamagui

Ensure the ThemePropagationTest component is inside main homescreen function and  the the scrollviewdemo component isn't.

https://github.com/GigaBigBoss/tamagui/blob/master/starters/next-expo-solito/packages/app/features/home/screen.tsx

**Comment by natew** [comment]
I think this is fixed in 201, if you can just lmk if that fixes.

**Comment by GigaBigBoss** [comment]
> I think this is fixed in 201, if you can just lmk if that fixes.

![image](https://user-images.githubusercontent.com/106954969/199437734-ce3d54dd-e94d-4e68-9179-89cda57ef289.png)
Issue still present

**Comment by natew** [comment]
Didn't realize you're working off a fork of the tamagui monorepo itself, that's a recipe for confusion because everything in `starters` isn't the same node modules as the root...

**Comment by natew** [comment]
this is actually an issue with <Group>... hadn't thought this one through, with flattening group will break :/ I am not the biggest fan of Group for this reason (cloning children), thinking of what would be best here..

**Comment by natew** [comment]
Fixed in https://github.com/tamagui/tamagui/commit/377d5b38b91489834ede6cefeab430ffaacaba9a

No longer doing weird stuff with size props in groups
