### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded" when using the tamagui Select component inside any tamagui Dialog

### ISSUE THREAD

**Issue by rajatkantinandi** [tamagui/tamagui#3224]
### Current Behavior

When we open the select inside a dialog, choose some value and the select is closed, it throws this error. It has something to do with the focus trapping code of Dialog. It does not happen when the Select component is rendered outside Dialog. The error is from FocusScope.

https://github.com/user-attachments/assets/b66ae1a0-1d11-4f27-b6a7-9b371078a53c

### Expected Behavior

No call stack size exceeded error should be thrown. 

### Tamagui Version

```markdown
1.124.4 and any older versions as well.
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Just render a tamagui select inside a tamagui dialog. When you choose some values inside the select, it throws maximum call stack error. Reproducable example: 
https://codesandbox.io/p/devbox/epic-cori-q4gnxn?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A9%2C9
```
Repro link: https://codesandbox.io/p/devbox/epic-cori-q4gnxn?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A9%2C9

### System Info

```markdown
System:
    OS: macOS 15.3
    CPU: (8) arm64 Apple M1
    Memory: 141.63 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.3 - ~/.nvm/versions/node/v18.20.3/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.20.3/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.3/bin/npm
    bun: 1.1.42 - ~/.bun/bin/bun
  Browsers:
    Chrome: 132.0.6834.160
    Edge: 132.0.2957.140
    Safari: 18.3
  npmPackages:
    @ag-grid-community/client-side-row-model: 31.0.3 => 31.0.3 
    @ag-grid-community/core: 31.0.3 => 31.0.3 
    @ag-grid-community/react: 31.0.3 => 31.0.3 
    @ag-grid-community/styles: 31.0.3 => 31.0.3 
    @babel/core: ^7.20.0 => 7.23.9 
    @babel/plugin-proposal-export-namespace-from: 7.18.9 => 7.18.9 
    @chakra-ui/live-region: 2.1.0 => 2.1.0 
    @dev-plugins/react-navigation: 0.0.5 => 0.0.5 
    @dev-plugins/react-query: 0.0.6 => 0.0.6 
    @jest/globals: 29.5.0 => 29.5.0 
    @lottiefiles/react-lottie-player: 3.5.3 => 3.5.3 
    @react-hook/async: 3.1.1 => 3.1.1 
    @react-native-community/datetimepicker: 7.7.0 => 7.7.0 
    @react-native-community/netinfo: 11.1.0 => 11.1.0 
    @react-navigation/native: 6.1.10 => 6.1.10 
    @react-navigation/stack: 6.3.21 => 6.3.21 
    @sentry/cli: 2.16.1 => 2.16.1 
    @sentry/react-native: ~5.20.0 => 5.20.0 
    @svgr/cli: 6.2.1 => 6.2.1 
    @tamagui/animations-react-native: 1.95.3 => 1.95.3 
    @tamagui/babel-plugin: 1.95.3 => 1.95.3 
    @tamagui/config: 1.95.3 => 1.95.3 
    @tamagui/react-native-media-driver: 1.95.3 => 1.95.3 
    @tamagui/shorthands: 1.95.3 => 1.95.3 
    @tamagui/themes: 1.95.3 => 1.95.3 
    @tanstack/react-query: 5.40.1 => 5.40.1 
    @testing-library/jest-native: 4.0.5 => 4.0.5 
    @testing-library/react-native: 11.0.0 => 11.0.0 
    @typeform/embed-react: 3.8.0 => 3.8.0 
    @types/file-saver: 2.0.7 => 2.0.7 
    @types/qs: 6.9.7 => 6.9.7 
    @types/react: ~18.2.45 => 18.2.55 
    @types/react-native-app-intro-slider: 4.0.0 => 4.0.0 
    @types/ua-parser-js: 0.7.36 => 0.7.36 
    @types/url-parse: 1.4.8 => 1.4.8 
    @types/uuid: 10.0.0 => 10.0.0 
    babel-plugin-module-resolver: 5.0.0 => 5.0.0 
    babel-plugin-transform-inline-environment-variables: 0.4.4 => 0.4.4 
    babel-preset-expo: ^10.0.0 => 10.0.2 
    cross-env: 7.0.3 => 7.0.3 
    emoji-regex: 10.4.0 => 10.4.0 
    expo: ~50.0.19 => 50.0.19 
    expo-application: ~5.8.4 => 5.8.4 
    expo-asset: ~9.0.2 => 9.0.2 
    expo-auth-session: 4.1.0 => 4.1.0 
    expo-av: ~13.10.6 => 13.10.6 
    expo-build-properties: ~0.11.1 => 0.11.1 
    expo-clipboard: ~5.0.1 => 5.0.1 
    expo-constants: ~15.4.6 => 15.4.6 
    expo-dev-client: ~3.3.12 => 3.3.12 
    expo-device: ~5.9.4 => 5.9.4 
    expo-file-system: ~16.0.9 => 16.0.9 
    expo-font: ~11.10.3 => 11.10.3 
    expo-image: ~1.10.6 => 1.10.6 
    expo-linear-gradient: ~12.7.2 => 12.7.2 
    expo-linking: ~6.2.2 => 6.2.2 
    expo-local-authentication: ~13.8.0 => 13.8.0 
    expo-optimize: 0.2.18 => 0.2.18 
    expo-random: ~13.6.0 => 13.6.0 
    expo-router: ~3.4.10 => 3.4.10 
    expo-secure-store: ~12.8.1 => 12.8.1 
    expo-sharing: ~11.10.0 => 11.10.0 
    expo-speech: 11.7.0 => 11.7.0 
    expo-splash-screen: ~0.26.5 => 0.26.5 
    expo-status-bar: ~1.11.1 => 1.11.1 
    expo-updates: ~0.24.13 => 0.24.13 
    expo-web-browser: ~12.8.2 => 12.8.2 
    file-saver: 2.0.5 => 2.0.5 
    fuse.js: 6.6.2 => 6.6.2 
    immer: 9.0.14 => 9.0.14 
    jest: 29.4.3 => 29.4.3 
    jest-expo: ~50.0.4 => 50.0.4 
    lottie-react-native: 6.5.1 => 6.5.1 
    nanoclone: 1.0.1 => 1.0.1 
    onesignal-expo-plugin: 2.0.3-beta.0 => 2.0.3-beta.0 
    qs: 6.10.3 => 6.10.3 
    react: 18.2.0 => 18.2.0 
    react-debounce-hook: 1.1.19 => 1.1.19 
    react-dom: 18.2.0 => 18.2.0 
    react-hook-form: 7.30.0 => 7.30.0 
    react-idle-timer: 5.7.2 => 5.7.2 
    react-native: 0.73.6 => 0.73.6 
    react-native-calendars: 1.1303.0 => 1.1303.0 
    react-native-confetti-cannon: 1.5.2 => 1.5.2 
    react-native-gesture-handler: ~2.14.0 => 2.14.1 
    react-native-get-random-values: 1.8.0 => 1.8.0 
    react-native-image-viewing-sieuhuflit: 0.2.5 => 0.2.5 
    react-native-markdown-display: 7.0.2 => 7.0.0-alpha.2 
    react-native-onesignal: 5.1.3 => 5.1.3 
    react-native-reanimated: ~3.6.2 => 3.6.2 
    react-native-restart: 0.0.24 => 0.0.24 
    react-native-safe-area-context: 4.8.2 => 4.8.2 
    react-native-screens: ~3.29.0 => 3.29.0 
    react-native-svg: 14.1.0 => 14.1.0 
    react-native-toast-notifications: 3.4.0 => 3.4.0 
    react-native-web: ~0.19.6 => 0.19.10 
    react-native-webview: 13.6.4 => 13.6.4 
    react-onesignal: 3.0.1 => 3.0.1 
    react-phone-number-input: 3.3.6 => 3.3.6 
    react-refresh: 0.14.0 => 0.14.0 
    react-smartbanner: 5.1.4 => 5.1.4 
    source-map-explorer: 2.5.3 => 2.5.3 
    tamagui: 1.95.3 => 1.95.3 
    ts-jest: 29.1.0 => 29.1.0 
    ts-node: 10.9.1 => 10.9.1 
    type-fest: 2.19.0 => 2.19.0 
    typescript: 5.6.3 => 5.6.3 
    ua-parser-js: 0.7.31 => 0.7.31 
    use-error-boundary: 2.0.6 => 2.0.6 
    uuid: 10.0.0 => 10.0.0 
    versiony: 2.0.1 => 2.0.1 
    zustand: 4.3.9 => 4.3.9
```

**Comment by rajatkantinandi** [comment]
Hi, @natew or anyone else have any suggestion as to what is going on here and how to prevent this behaviour? This is causing the page unresponsive sometimes when multiple selects are rendered inside a dialog. Is there a way to disable focus trapping for the dialog or some other solution? We are kind of stuck here. Please help us find a solution since this is critical for our app.

**Comment by zarin-maruf** [comment]
@natew can you please assign this to me?

**Comment by rajatkantinandi** [comment]
@natew any update on this?

**Comment by natew** [comment]
This maybe fixed in the latest, we fixed a few things related to this. @rajatkantinandi can you verify?

**Comment by rajatkantinandi** [comment]
Sorry, couldn't check earlier but it is still happening on version 1.126.16, which was released after this issue was closed. I will verify if it is happening in the latest version as well.

**Comment by hackily** [comment]
I see this issue too, with latest. I can recreate in the docs
https://tamagui.dev/ui/dialog

https://github.com/user-attachments/assets/d00a6e06-a2d3-44bc-bdc4-94234ec41723
