### ISSUE TITLE
Texts in Buttons and Cards disappear on iOS

### ISSUE THREAD

**Issue by Finteria** [tamagui/tamagui#3364]
### Current Behavior

Texts in Buttons and Cards disappear on iOS if **Increase Contract** is enabled in Accessibility settings

The issue happens on different iPhones 12, 14,15 if **Increase Contract** is enabled.

### Expected Behavior

Texts must not disappear after enabling **Increase Contract** is enabled in Accessibility settings

### Tamagui Version

```markdown
1.125.26
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
Just go to iOS settings > Accessibility > enable **Increase Contrast**
```

### System Info

```markdown

```

**Comment by hirvesh** [comment]
I am having a similar issue but when starting the app in dark mode, then switching to light mode; the font text stays white/dissapears.

**Comment by Finteria** [comment]
@hirvesh does it work fine if you disable  **Increase Contrast** ?

**Comment by Finteria** [comment]
Actually, the issue is now resolved. It was related to using v3 configs with version 1.125.26.

I migrated to v4 config but reused some of old themes from v3 and it worked fine.

**Comment by Quentie** [comment]
We’re experiencing a similar issue, and upgrading to the v4 config didn’t seem to resolve it. Anything that gets its color/backgroundcolor ... from the theme rather than directly from inline styles appears to be broken in high contrast accessibility mode.
