### ISSUE TITLE
Starter Next JS production build crashes with "Missing theme."

### ISSUE THREAD

**Issue by Sir-hennihau** [tamagui/tamagui#3372]
### Current Behavior

When using the app router and opening your app in the browser, the page will fail with `Application error: a client-side exception has occurred (see the browser console for more information).`.
The console will give the following error: `Error: Missing theme.`

### Expected Behavior

Both routers should work.

### Tamagui Version

```markdown
Latest
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
- Create a new starter repo
- Run cd apps/next && yarn build && yarn serve
- Press on "Change router: app" -> The app will crash


2nd reproduction case:
- host a fresh tamagui starter on vercel
- Press on "Change router: app" -> The app will crash
```

![Image](https://github.com/user-attachments/assets/431dae95-469d-4e69-973a-0837b21c3ef7)

**Comment by Jcmza** [comment]
Did you manage to solve this issue? I'm experiencing the same problem

**Comment by Sir-hennihau** [comment]
@Jcmza no. im even surprised that no one else reported it before me. this is super critical, since you cant use the app router at all

**Comment by kelvanb97** [comment]
Also hitting this with a rather simple configuration. Everything is working as expected locally:

```tsx
//NextTamaguiProvider.tsx
return (
	<NextThemeProvider forcedTheme="light">
		<TamaguiProvider
			config={config}
			disableInjectCSS
			defaultTheme={rootTheme}
		>
			{children}
		</TamaguiProvider>
	</NextThemeProvider>
)
```

**Comment by RobSchilderr** [comment]
Production builds crash with "Missing theme" when using the App Router, which makes it essentially impossible to use Tamagui in modern Next.js projects. The App Router is now the standard for new projects, so this issue severely limits real-world adoption.

Really hoping this can be prioritized — any known workarounds or updates would be greatly appreciated!

**Comment by WillRMachado** [comment]
Same issue here!


@RobSchilderr 

I've managed to get it working by deleting everything under /pages/ except for the /api/ folder
and implement a new provider for tamagui/nextStyle

and my files are as following

/app/NextTamaguiProvider


```

'use client';

import '@tamagui/core/reset.css';
import '@tamagui/font-inter/css/400.css';
import '@tamagui/font-inter/css/700.css';
import '@tamagui/polyfill-dev';

import type { ReactNode } from 'react';
import { StyleSheet } from 'react-native';
import { useServerInsertedHTML } from 'next/navigation';
import { NextThemeProvider, useRootTheme } from '@tamagui/next-theme';
import { config } from '@my/ui';
import { Provider } from 'app/provider';
import { TamaguiProvider } from 'tamagui';

export const NextTamaguiProvider = ({ children }: { children: ReactNode }) => {
  const [theme, setTheme] = useRootTheme();

  useServerInsertedHTML(() => {
    // @ts-ignore
    const rnwStyle = StyleSheet.getSheet();
    return (
      <>
        <style dangerouslySetInnerHTML={{ __html: rnwStyle.textContent }} id={rnwStyle.id} />

        <style
          dangerouslySetInnerHTML={{
            // the first time this runs you'll get the full CSS including all themes
            // after that, it will only return CSS generated since the last call
            __html: config.getNewCSS(),
          }}
        />

        <style
          dangerouslySetInnerHTML={{
            __html: config.getCSS({
              // if you are using "outputCSS" option, you should use this "exclude"
              // if not, then you can leave the option out
              exclude: process.env.NODE_ENV === 'production' ? 'design-system' : null,
            }),
          }}
        />

        <script
          dangerouslySetInnerHTML={{
            // avoid flash of animated things on enter:
            __html: `document.documentElement.classList.add('t_unmounted')`,
          }}
        />

        <style jsx global>{`
          html {
            font-family: 'Inter';
          }
        `}</style>
      </>
    );
  });

  return (
    <NextThemeProvider onChangeTheme={(next) => setTheme(next as any)}>
      <TamaguiProvider config={config} defaultTheme={theme}>
        <Provider defaultTheme={theme}>
          {children}
        </Provider>
      </TamaguiProvider>
    </NextThemeProvider>
  );
};

```

/app/layout



```
import type { Metadata } from 'next';
import { NextTamaguiProvider } from './NextTamaguiProvider';

export const metadata: Metadata = {
  title: 'Tamagui • App Router',
  description: 'Tamagui, Solito, Expo & Next.js',
  icons: '/favicon.ico',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning className="light_theme">
      <body>
        <NextTamaguiProvider>{children}</NextTamaguiProvider>
      </body>
    </html>
  );
}



```



/app/_app


```import { NextThemeProvider, useRootTheme } from '@tamagui/next-theme'
import { Provider } from 'app/provider'
import { AppProps } from 'next/app'
import Head from 'next/head'
import { useMemo } from 'react'
import { TamaguiProvider } from 'tamagui'
import config from '../tamagui.config'

export default function App({ Component, pageProps }: AppProps) {
  const [theme, setTheme] = useRootTheme()

  const contents = useMemo(() => {
    return <Component {...pageProps} />
  }, [Component, pageProps])

  const handleThemeChange = (nextTheme: string) => {
    setTheme(nextTheme as any)
  }

  return (
    <>
      <Head>
        <title>Med App</title>
        <meta name="description" content="Med App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextThemeProvider onChangeTheme={handleThemeChange}>
        <TamaguiProvider config={config} defaultTheme={theme}>
          <Provider>{contents}</Provider>
        </TamaguiProvider>
      </NextThemeProvider>
    </>
  )
} 

```




and my /pakages/app/providers/index


```
import { useColorScheme } from 'react-native';
import {
  CustomToast,
  TamaguiProvider,
  type TamaguiProviderProps,
  ToastProvider,
  config,
  isWeb,
  Text,
} from '@my/ui';
import { ToastViewport } from './ToastViewport';
import { QueryProvider } from './query-client';

export function Provider({ children, ...rest }: Omit<TamaguiProviderProps, 'config'>) {
  const colorScheme = useColorScheme();

  return (
    <QueryProvider>
      <TamaguiProvider
        config={config}
        defaultTheme={colorScheme === 'dark' ? 'dark' : 'light'}
        {...rest}
      >
        <ToastProvider swipeDirection='horizontal' duration={6000} native={isWeb ? [] : ['mobile']}>
          {children}
          <CustomToast />
          <ToastViewport />
        </ToastProvider>
      </TamaguiProvider>
    </QueryProvider>
  );
}


```




As you can see it'll double-wrap the provider, it might be fixable by adding a if statement for each Platform


I'm only listing it here as a workaround for the time beeing

**Comment by WillRMachado** [comment]
Same Here

@RobSchilderr 

What I did as workaround was to drop the whole/page/ folder and focus only on /app/


which was easy since I've just started the project, I understand it might not be so simple in a larger one

**Comment by RobSchilderr** [comment]
> Same Here
> 
> [@RobSchilderr](https://github.com/RobSchilderr)
> 
> What I did as workaround was to drop the whole/page/ folder and focus only on /app/
> 
> which was easy since I've just started the project, I understand it might not be so simple in a larger one

What do you mean exactly?

**Comment by leandrop98** [comment]
I had the same issue and fixed it by downgrading the tamagui config version in `packages/config/src/tamagui.config.ts`

```
// import { defaultConfig } from '@tamagui/config/v4' // before
import { config as defaultConfig } from '@tamagui/config/v3' // downgrade to v3
import { createTamagui } from 'tamagui'
import { bodyFont, headingFont } from './fonts'
import { animations } from './animations'

export const config = createTamagui({
  ...defaultConfig,
  animations,
  fonts: {
    body: bodyFont,
    heading: headingFont,
  },
})

```

**Comment by RobSchilderr** [comment]
Should be solved in latest Tamagui version. Didn't test it myself yet, will do tomorrow. Let me know if anyone does!

**Comment by Sir-hennihau** [comment]
@RobSchilderr has there been a pull request to fix it?

**Comment by kelvanb97** [comment]
@Sir-hennihau just tested. `v4` is still broken on the latest version, which is `1.125.35`. Checking if downgrading from `@tamagui/config/v4` to `@tamagui/config/v3` fixes the issue.

**Comment by kelvanb97** [comment]
Confirmed. Downgrading the config from v4 to v3 fixes the issue.

**Comment by RobSchilderr** [comment]
> Hey, folks. I fixed that error in the latest PR and added an option: `disableThemesBundleOptimize` into `withTamagui` and update `starter-free` latest version. https://github.com/tamagui/starter-free/blob/e948b66cc81b71ca727d9d771551598532feecd4/apps/next/next.config.js#L27C5-L27C32

First of all, thanks so much for the quick fix — really appreciated!

Just some feedback: Nate has been focusing on making Tamagui easier to adopt recently and from my experience, extra config flags (like booleans or env vars) can easily be missed, and often the solution ends up buried in Discord threads. That can make onboarding feel harder than it should be.

Not sure if it’s possible, but would it make sense to enable this automatically when `appDir` is true (and maybe on Next.js 15 / React 19)? Or maybe there’s a way to solve it without requiring another manual config step?

**Comment by baronha** [comment]
> Also, while I appreciate your thought of adding `disableThemesBundleOptimize`, I’m not sure it’s the ideal long-term fix. Since `appDir: true` is already set, wouldn’t that be enough to infer this is a Next.js App Router setup and apply a fix automatically? Or at least something that is not "disabling optimizations", we want the optimizations!

Yah, This is only a temporary solution. I will find the deep of the error

**Comment by nnphong1904** [comment]
You need to import the tamagui.css into the `<Head>` by adding this `<link rel="stylesheet" href="/tamagui.css" />`

**Comment by dhatGuy** [comment]
I'm experiencing this on native after upgrading to expo 53

**Comment by baronha** [comment]
> I'm experiencing this on native after upgrading to expo 53

We are solving this.

**Comment by JamesMitofsky** [comment]
Any progress or news on this, @baronha ? I'm dealing with the problem on Next right now, but I have an important mobile deployment scheduled for next week, so just wanted to proactively check in.
