### ISSUE TITLE
Error: Can't find Tamagui configuration.

### ISSUE THREAD

**Issue by irfanundevli** [tamagui/tamagui#3442]
### Current Behavior

Getting error below while starting the app with tamagui@1.126.8 and expo@53.0.8 versions.

"
Warning: Error: Can't find Tamagui configuration.
    
99% of the time this is due to having mis-matched versions of Tamagui dependencies.
Ensure that every "tamagui" and "@tamagui/*" dependency is pinned to exactly the same version.
"

[package.json](https://github.com/user-attachments/files/20109585/package.json)

### Tamagui Version

```markdown
1.126.8
```

### Platform (Web, iOS, Android)

```markdown
iOS
```

### Reproduction

```markdown
**Steps to reproduce:** 

1. Create an app with`npx create-expo-app@latest --template blank-typescript` command
2. Install dependencies to use tamagui (tamagui, @tamagui/config, react-native-svg, @tamagui/lucide-icons' )
3. Update App.tsx file with code below. Attached the package.json file as well.
4. Start the expo app.

**App.tsx**  file content
`
import { StatusBar } from "expo-status-bar";
import { StyleSheet, Text, View } from "react-native";
import { defaultConfig } from "@tamagui/config/v4";
import { Button, createTamagui, TamaguiProvider } from "tamagui";
import { ChevronDown } from "@tamagui/lucide-icons";

// Tamagui config
export const config = createTamagui(defaultConfig);
type CustomConfig = typeof config;
declare module "tamagui" {
  // This is a workaround for the TamaguiProvider to accept the custom config
  interface TamaguiCustomConfig extends CustomConfig {}
}

export default function App() {
  return (
    <TamaguiProvider config={config} defaultTheme="light">
      <View style={styles.container}>
        <Button iconAfter={ChevronDown}>Click Me!</Button>
        <StatusBar style="auto" />
      </View>
    </TamaguiProvider>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
});
`
```

### System Info

```markdown
System:
    OS: macOS 15.3.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 34.93 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.15.0 - ~/.nvm/versions/node/v22.15.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v22.15.0/bin/yarn
    npm: 10.9.2 - ~/.nvm/versions/node/v22.15.0/bin/npm
  Browsers:
    Chrome: 135.0.7049.115
    Safari: 18.3.1
  npmPackages:
    @babel/core: ^7.25.2 => 7.27.1
    @tamagui/config: ^1.126.8 => 1.126.8
    @tamagui/lucide-icons: ^1.126.8 => 1.126.8
    @types/react: ~19.0.10 => 19.0.14
    expo: ~53.0.8 => 53.0.8
    expo-status-bar: ~2.2.3 => 2.2.3
    react: 19.0.0 => 19.0.0
    react-native: 0.79.2 => 0.79.2
    react-native-svg: ^15.11.2 => 15.11.2
    tamagui: ^1.126.8 => 1.126.8
    typescript: ~5.8.3 => 5.8.3
```

**Comment by floklein** [comment]
Oh my god I spent the day on that, thinking it was my setup.
Even the [Expo guide's template](https://tamagui.dev/docs/guides/expo) doesn't work.

**Comment by irfanundevli** [comment]
the issue was fixed with 1.126.9 version.

**Comment by cgorrieri** [comment]
@irfanundevli did you see my comment that the basic yarn create tamagui@latest --template expo-router command from the guide doesn't work? It is with the version you say it was fixed.

**Comment by JoeSlain** [comment]
> [@irfanundevli](https://github.com/irfanundevli) did you see my comment that the basic yarn create tamagui@latest --template expo-router command from the guide doesn't work? It is with the version you say it was fixed.

Still doesn't work, did you manage to make it work @cgorrieri ?

**Comment by cgorrieri** [comment]
> > [@irfanundevli](https://github.com/irfanundevli) did you see my comment that the basic yarn create tamagui@latest --template expo-router command from the guide doesn't work? It is with the version you say it was fixed.
> 
> Still doesn't work, did you manage to make it work [@cgorrieri](https://github.com/cgorrieri) ?

I found the issue, if you run `yarn create tamagui --template expo-router` then it works

**Comment by StanAngeloff** [comment]
This might be a long shot, but for me this was caused by having `defaultTheme={...}` on the `<TamaguiProvider />`. The theme I was referencing didn't actually exist. What tipped me off was the message _"Warning: Error: Can't find Tamagui configuration."_ is held in a constant called [`MISSING_THEME_MESSAGE`](https://github.com/tamagui/tamagui/blob/main@%7B2025-07-01%7D/code/core/web/src/constants/constants.ts#L25).
