### ISSUE TITLE
Button text colour and font-family are not correctly set since 1.133.0

### ISSUE THREAD

**Issue by SHergibo** [tamagui/tamagui#3617]
### Current Behavior

Since the 1.133.0 version, the font-family and the colour of a text Button are not correctly set.

Before (with version 1.132.25):

<img width="385" height="78" alt="Image" src="https://github.com/user-attachments/assets/555de3f8-ecc3-4fa6-9b92-9d19ef5c6794" />

After (with version 1.333.0 or 1.333.1):

<img width="379" height="75" alt="Image" src="https://github.com/user-attachments/assets/a0baffdc-9f36-42c0-b67f-6c569f787344" />

### Expected Behavior

The style for the text of the Button component needs to be correctly set.

### Tamagui Version

```markdown
v1.133.0
```

### Platform (Web, iOS, Android)

```markdown
Web
```

### Reproduction

```markdown
Component used:



import { Button } from 'tamagui';
import React from 'react';

export const ButtonComp = () => {
  return (
    <Button
      backgroundColor="$primary"
      borderColor="$primary"
      borderRadius={12}
      borderWidth={1.5}
      color="$white"
      fontSize={16}
      fontWeight="600"
      height={55}
    >
      TEXT
    </Button>
  );
};


tamagui.config:



import { createTamagui } from 'tamagui';
import { defaultConfig } from '@tamagui/config/v4';
import { interFont } from './fonts';
import { tamagui_themes } from './themes';

export const config = createTamagui({
  ...defaultConfig,
  defaultFont: 'body',
  fonts: interFont,
  themes: tamagui_themes.themes,
});

export type MasanaProConfigType = typeof config;


interFont:



import { createFont } from '@tamagui/core';

export const interFont = {
  body: createFont({
    family: 'Inter, Helvetica, Arial, sans-serif',
    letterSpacing: {},
    lineHeight: {
      10: 46,
      2: 15,
      3: 17,
      4: 20,
      5: 24,
      7: 29,
      8: 33,
      9: 39,
    },
    size: {
      10: 38,
      2: 12,
      3: 14,
      4: 16,
      5: 18,
      7: 22,
      8: 26,
      9: 32,
    },
    weight: {
      4: '400',
    },
  }),
};
```

### System Info

```markdown

```

**Comment by SHergibo** [comment]
Here is a correct reproduction:

https://codesandbox.io/p/github/tamagui/starter-free/csb-9lh847/draft/epic-maxwell?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx%3A28%2C35

**Comment by noeljackson** [comment]
I am having this issue as well.

**Comment by natew** [comment]
Fixed on v1.134.2

**Comment by yummydirtx** [comment]
Still broken for me on v1.134.2:

On v1.134.2:
<img width="1222" height="207" alt="view on v1.134.2" src="https://github.com/user-attachments/assets/26066f69-00c4-4fc8-8edf-091ccc69e21f" />

On v1.132.7:

<img width="1222" height="207" alt="view on v1.132.7" src="https://github.com/user-attachments/assets/5b7e08ea-d853-4875-a12f-dfa4ea7ade89" />

**Comment by natew** [comment]
Hm it fixed at least the case I tested on. I’ll check your repo soon.

**Comment by natew** [comment]
Though not sure I see what is happening in the screenshot it’s red and grey like the top one but missing the third button.

**Comment by yummydirtx** [comment]
> Though not sure I see what is happening in the screenshot it’s red and grey like the top one but missing the third button.

Haha sorry, I'm comparing the live prod version vs the new version I'm developing after I tried upgrading Tamagui. Here's a screenshot of the dev build after rolling back the update: 

<img width="1222" height="207" alt="Image" src="https://github.com/user-attachments/assets/fff71dfa-c122-4c11-8279-f7929fe779cf" />

I'll give you access to the repo.

**Comment by isaachinman** [comment]
Hit this myself after upgrading (`1.134.4`), have to downgrade again. Seeing serif fonts on SizableText, ButtonText, etc.

Can repro on `1.135.0` as well.

Regression was introduced in `1.133.0`.

**Comment by isaachinman** [comment]
Actually, I can repro in a small subset of cases even with `1.132.25`. Had to downgrade all the way back to `1.132.15`.

I can clearly see this is an extremely fast-paced project maintained mostly by a single dev, which is hugely impressive. I would be willing to help with some test coverage if desired.

**Comment by sagefarrenholz** [comment]
having same problem. note that 
```
<Button><Text>Word</Text></Button>
```
works fine

**Comment by anhquan291** [comment]
Guys, the latest version already includes this fix!

**Comment by jinyongnan810** [comment]
For our app, the button font color still not applying correctly in version `1.135.2`. when the button
with a styled button theme set like this, the font color won't change from default color `white` to disabled color `$gray300` when button is disabled (though anything else like background and border color is changed correctly).
```ts
import { Button as BaseButton, styled } from 'tamagui';
export const Button = styled(BaseButton, {
  borderRadius: '$full',
  fontWeight: 'bold',

  variants: {
    layout: {
      medium: {
        height: 48,
        minWidth: '100%',
      },
    },
    theme: {
      primary: {
        backgroundColor: '$main500',
        color: 'white',
        pressStyle: {
          backgroundColor: '$main600',
        },
        disabledStyle: {
          backgroundColor: '$gray300',
          color: '$gray500',
        },
      },
    },
  } as const,

  defaultVariants: {
    theme: 'primary',
    layout: 'medium',
  },
});
```

**Comment by JavanPoirier** [comment]
> Actually, I can repro in a small subset of cases even with `1.132.25`. Had to downgrade all the way back to `1.132.15`.
> 
> I can clearly see this is an extremely fast-paced project maintained mostly by a single dev, which is hugely impressive. I would be willing to help with some test coverage if desired.

Still having this issue on 1.138.1, I downgraded to 1.132.15 and it did indeed fix it.  

```
const ButtonFrame = styled(ThemeableStack, {
       ...
	variants: {
               ...
		variant: {
			...
			link: {
				color: "hotpink",
				hoverStyle: {
					color: "red", <--- NOTE: Color does not get passed to children to be used with `$color`.
				},
			},
		},
                ...
	} as const,

	defaultVariants: {
		unstyled: process.env.TAMAGUI_HEADLESS === "1",
	},
});

const ButtonText = styled(SizableText, {
	variants: {
		variant: {
			link: {
				color: "$color", <--- This does not work in most recent version. Downgraded to 1.132.15
			},
		},
	} as const,

	defaultVariants: {
		unstyled: process.env.TAMAGUI_HEADLESS === "1",
	},
});
```
