### ISSUE TITLE
Regression using nested surface1, surface2 themes

### ISSUE THREAD

**Issue by pkfms** [tamagui/tamagui#3673]
### Current Behavior

Using tamaguiThemes import from @tamagui/config/v4
Using surface3 theme inside a surface1 theme has stopped working since version 1.137.3
In 1.137.2 the inner surface3 stack will have classes t_sub_theme t_blue_surface3
In 1.137.3 and later it will have only t_sub_theme t_surface3 <- blue is gone and it will only have light/dark surface3 applied

```
<ThemeableStack theme={'surface1'} padded radiused bordered backgrounded>
    <Paragraph>theme surface1</Paragraph>
    <ThemeableStack theme={'surface3'} padded radiused bordered backgrounded>
        <Paragraph>theme surface3</Paragraph>
    </ThemeableStack>
</ThemeableStack>
```

<img width="271" height="182" alt="Image" src="https://github.com/user-attachments/assets/0a8a9145-a045-4325-87f2-c347856987b9" />

<img width="275" height="188" alt="Image" src="https://github.com/user-attachments/assets/d6dc4467-6e5e-43c5-82a2-968f41f474d1" />

### Expected Behavior

The blue theme should still be used when nesting child themes

### Tamagui Version

```markdown
1.138.1
```

### Platform (Web, iOS, Android)

```markdown
web
```

### Reproduction

```markdown
https://codesandbox.io/p/github/pkfms/tamagui-example/nested-surface
```

### System Info

```markdown

```

**Comment by natew** [comment]
This was fixed in commit 5839319146 - the theme resolution now tries the full parent context (light_blue_surface3) before falling back to just the scheme (light_surface3). Should be in v1.137.3+. Added some integration tests to catch this going forward.

**Comment by pkfms** [comment]
@natew  I still can't get this to work on the latest version with tamaguiThemes from config v4. The nested surface3 is as the right screenshot. I added tamagui config to example above, if there is something that should be done different. This worked before 1.137.3

**Comment by sohcah** [comment]
Hitting this issue when upgrading from `1.350.0` to `1.141.2` myself

**Comment by natew** [comment]
@sohcah want to help me look over #3773 and see if this would fix
