### ISSUE TITLE
Incorrect dependency management

### ISSUE THREAD

**Issue by nandorojo** [tamagui/tamagui#439]
Tamagui currently has the following practices in its package, which are dangerous for open source projects:

1. **`react` is in `dependencies`.** This is guaranteed to have multiple hook call bugs with clashing versions. This should be a `peerDependency`, but more likely, a `devDependency`, since `peerDependencies` throw unnecessary warnings for monorepo users.
  a. I just tried spinning this up with a basic Expo app, and none of it worked because of many tamagui packages installing React. Libraries should never have React as a direct dependency.
3. **Dependencies don't respect semver.** One example is [`react-native-svg` inside of `@tamagui/lucide-icons`](https://github.com/tamagui/tamagui/blob/master/packages/lucide-icons/package.json#L27). Once again, this should be a peer dependency for a number of reasons. 
  a. First, transitive dependencies don't get linked natively.
  b. Second, Tamagui should be specifying the major version of `react-native-svg` which it's compatible with.
  c. **However**, it is not doing this properly. Instead, tamagui uses very dangerous versioning methods: `"react-native-svg": ">=12"`. This means that apps could download v12 or v13 (which happened to me). It should be `^12.3.2` style instead.

For example: `@tamagui/get-button-sized` has `react: ">=18"` as a _direct dependency._ Instead, it should have `^18.0.0` as a `devDependency`. The usage of `>=` isn't safe for semver.

**Comment by natew** [comment]
Yea good points, the >= happened in frustration over issues, but peerDeps + devDeps is the solution.

Fixed in 3c0f3452cde25fb2c6ac8a4ed7e5bee0ff21830d `rc.4`

**Comment by nandorojo** [comment]
Good looks on the fast update!

**Comment by nderscore** [comment]
@natew this is still happening on the `tamagui` package. I think these should be moved to peer deps?

https://github.com/tamagui/tamagui/blob/c6d31da34ac2ab2a49545a21f0a395cf0564bb38/packages/tamagui/package.json#L71-L72

**Comment by nandorojo** [comment]
The expo packages should too.

**Comment by natew** [comment]
Oh I think manypkg is "fixing" these back... let me see.

**Comment by natew** [comment]
Ah ok just forgot that one, release going out now fixing

**Comment by nandorojo** [comment]
thanks for the quick fixes here. fyi – `expo-device-orientation` should be a peer dep too (or could just be removed in favor of dimensions maybe?)

**Comment by nandorojo** [comment]
`expo-linear-gradient` is still broken as well:

```sh
=> Found "expo-linear-gradient@12.0.1"
info Has been hoisted to "expo-linear-gradient"
info Reasons this module exists
   - "workspace-aggregator-7f877f60-77d5-44ef-b2a0-ebb3aa47eb8b" depends on it
   - Hoisted from "_project_#speed#expo-linear-gradient"
   - Hoisted from "_project_#tix-native#expo-linear-gradient"
info Disk size without dependencies: "260KB"
info Disk size with unique dependencies: "260KB"
info Disk size with transitive dependencies: "260KB"
info Number of shared dependencies: 0
=> Found "tamagui#expo-linear-gradient@11.4.0"
info This module exists because "_project_#@beatgig-tickets#ds#tamagui" depends on it.
info Disk size without dependencies: "252KB"
info Disk size with unique dependencies: "252KB"
info Disk size with transitive dependencies: "252KB"
info Number of shared dependencies: 0
```
