### ISSUE TITLE
"yarn web" and "yarn native" commands throw error

### ISSUE THREAD

**Issue by webbyink** [tamagui/tamagui#46]
I have set up the starter template using "npx create-tamagui-app@latest". But when I run the command "yarn web", it throws the following error:

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
 web  | withTamagui skipping resolving @gorhom/bottom-sheet$
 web  | exclude /react-native-web/.*(Switch|ProgressBar|Picker|Animated|AnimatedFlatList).*/
info  - automatically enabled Fast Refresh for 1 custom loader
 ssr  | withTamagui skipping resolving @gorhom/bottom-sheet$
 ssr  | exclude /react-native-web/.*(Switch|ProgressBar|Picker|Animated|AnimatedFlatList).*/
 ssr  | withTamagui skipping resolving @gorhom/bottom-sheet$
 ssr  | exclude /react-native-web/.*(Switch|ProgressBar|Picker|Animated|AnimatedFlatList).*/
      | patch dist\tamagui-exports.js
      | patch dist\cjs\tamagui-exports.js
      | patch dist\tamagui-exports.js
      | patch dist\cjs\tamagui-exports.js
      | patch dist\tamagui-exports.js
      | patch dist\cjs\tamagui-exports.js
wait  - compiling...
error - ./pages/_app.tsx
Error: ENOENT: no such file or directory, open 'D:\rn-tamagui\node_modules\react-native-web\dist\cjs\index.js\dist\tamagui-exports.js'

For "yarn native":

Android Bundling failed 4272ms
index.js: [BABEL] D:\rn-tamagui\apps\expo\index.js: ENOENT: no such file or directory, open 'D:\rn-tamagui\node_modules\react-native-web\dist\cjs\index.js\dist\tamagui-exports.js' (While processing: "D:\\rn-tamagui\\node_modules\\@tamagui\\babel-plugin\\dist\\cjs\\index.js")
Error: [BABEL] D:\rn-tamagui\apps\expo\index.js: ENOENT: no such file or directory, open 'D:\rn-tamagui\node_modules\react-native-web\dist\cjs\index.js\dist\tamagui-exports.js' (While processing: "D:\\rn-tamagui\\node_modules\\@tamagui\\babel-plugin\\dist\\cjs\\index.js")
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at patchReactNativeWeb (D:\rn-tamagui\node_modules\@tamagui\static\dist\cjs\patchReactNativeWeb.js:37:8)
    at snackBabelPlugin (D:\rn-tamagui\node_modules\@tamagui\babel-plugin\dist\cjs\index.js:62:43)
    at D:\rn-tamagui\node_modules\@babel\helper-plugin-utils\lib\index.js:22:12
    at sync (D:\rn-tamagui\node_modules\@babel\core\lib\gensync-utils\async.js:38:25)
    at sync (D:\rn-tamagui\node_modules\gensync\index.js:182:19)
    at D:\rn-tamagui\node_modules\gensync\index.js:210:24
    at Generator.next (<anonymous>)

**Comment by natew** [comment]
This should be fixed with the latest, try a fresh install and let me know.

**Comment by webbyink** [comment]
> This should be fixed with the latest, try a fresh install and let me know.

After deleting all npm & yarn global cache and the tamagui starter template, I installed the template fresh but the problem persists.

**Comment by natew** [comment]
Can you give OS, node info?

**Comment by webbyink** [comment]
> Can you give OS, node info?

OS: Windows 10
Node: 14 & Node: 16

**Comment by webbyink** [comment]
Sorry for marking the issue as closed accidentally.

**Comment by maitriyogin** [comment]
I get the same, created a fresh expo project, tried to copy over the relevant tamagui config and dependencies from the starter project.
Run `yarn start`
and get
`
Unable to resolve module react-native-web/dist/cjs/tamagui-exports from /Users/stephenwhite/projects/maitriyogin/callista/news-reader/node_modules/@tamagui/core/dist/cjs/constants/rnw.js: react-native-web/dist/cjs/tamagui-exports could not be found within the project or in these directories:
  node_modules/@tamagui/core/node_modules
  node_modules
  ../../../node_modules
  ../../../../node_modules
  25 | const rnw = {};
  26 | if (process.env.IS_STATIC === "is_static") {
> 27 |   Object.assign(rnw, interopRequire(require("react-native-web/dist/cjs/tamagui-exports")));
     |                                              ^
  28 | } else if (process.env.TAMAGUI_TARGET === "web") {
  29 |   Object.assign(rnw, interopRequire(require("react-native-web").TamaguiExports));
  30 | }

`

I can provide more info but just thought I'd throw this out for now to see if this rung any bells ...
/Stephen.

**Comment by natew** [comment]
Tested on the latest and it seems fine, lmk if still a bug
