### ISSUE TITLE
[bug] `NextThemeProvider` `next/head` warning

### ISSUE THREAD

**Issue by arjunnaha** [tamagui/tamagui#488]
**Describe the bug**
When using the starter, the app is wrapped in `NextThemeProvider`, which generates a warning:

![image](https://user-images.githubusercontent.com/7504589/210381802-dbe73b95-035c-42a6-a88a-210a44dc82b9.png)

Which comes from the theme switching script inserted using `NextHead` in [`NextTheme.tsx`](https://github.com/tamagui/tamagui/blob/master/packages/next-theme/src/NextTheme.tsx#L336).

**To Reproduce**
Run the starter, and see the browser console.

I've added the [debug flag and output logs](https://github.com/arjunnaha/tamagui/blob/5d1bed0714b42b44ab5cda9896acf409a1354591/packages/next-theme/src/NextTheme.tsx), but not sure how useful they'll be here.

**System Info (please complete the following information):** 

```
╰> npx envinfo --system --npmPackages --binaries --browsers

  System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 84.89 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 3.2.3 - ~/.yarn/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 15.6.1
  npmPackages:
    @babel/runtime: ^7.18.9 => 7.20.6
    @manypkg/cli: ^0.19.1 => 0.19.2
    @types/react: ^18.0.15 => 17.0.21
    @types/react-native: ^0.69.6 => 0.69.15
    eslint: ^8.21.0 => 8.28.0
    prettier: ^2.7.1 => 2.8.0
    turbo: ^1.4.2 => 1.6.3
    typescript: ^4.7.4 => 4.9.3
```

---

- [x] yarn.lock or similar
- [x] If it's a specific file, add `//! debug` to the top (the `!` works in esbuild compiled packages but not necessary always) and include that (only for compiler, but helps to know if it's on or off).
- [x] Run your server/bundler with `DEBUG=tamagui` and include that output at the bottom.

**Comment by natew** [comment]
Fixed in 33caf842360d9d0febd7608228065f2f86d8e7f4

**Comment by criszz77** [comment]
I can still reproduce it with starter template: 

![image](https://user-images.githubusercontent.com/55203625/213889552-68c922d1-8751-4c97-b78b-4f555498d9d7.png)

**Comment by natew** [comment]
I reverted it because it was causing a flash of unstyled content. Ideally we can just remove Tamagui next-themes and have it use the official next-themes, I think I forked it for some reason but that should be fixed or easy to upstream. On Jan 21, 2023, at 12:33 PM, Ovidiu Cristescu ***@***.***> wrote:﻿
I can still reproduce it with starter template:

**Comment by KaivG** [comment]
Hi, I also noticed this warning with the current starter project.

@natew  Could the flash of unstyled content be solved with one of the loading strategies discussed here?

https://nextjs.org/docs/api-reference/next/script

I am just starting out with next.js so unfortunately wouldn't know how to go about testing this myself.

**Comment by matteo-hertel** [comment]
@natew should this be reopened if the fix was reverted? the issue is still present
