### ISSUE TITLE
[bug] Image.prefetch is not a function. Looks like static functions from Image RNW are not present.

### ISSUE THREAD

**Issue by raphaelm-gioa** [tamagui/tamagui#818]

**Comment by natew** [comment]
Fixed in 1.9.7, lmk if still breaking for you.

**Comment by raphaelm-gioa** [comment]
Thanks for the care! I still encounter the issue after 1.9.8 though 😕

**Comment by natew** [comment]
Oh I thought you meant the ref doesn’t get the static methods. 1.9.10 should fix.
