### ISSUE TITLE
(Hover/Focus/etc) Style not applied on variants 

### ISSUE THREAD

**Issue by VladyslavKochetkov** [tamagui/tamagui#934]
### Current Behavior

When applying styling using variants and setting a conditional style (for example, hover) it doesn't get set and is overwritten by the default theme styles, for example, the border is overwritten by `borderColorHover` set in theme. 

<img width="322" alt="image" src="https://user-images.githubusercontent.com/33583906/231322162-ea5a4dd6-fc71-410b-9500-c2067161004f.png">

https://user-images.githubusercontent.com/33583906/231321676-79fbd0d7-291b-4388-835c-47b2c109eda6.mov

### Expected Behavior

Effect styles take preference to those defined when defining a component over those defined in a theme. 

#### !!Note!!
This can be mitigated by removing the  `backgroundHover`, `backgroundPress`, `borderColorHover`, `borderColorPress`, `borderColorFocus` keys on the theme you're using.

> Recording was produced by toggling "hover" element stage in inspect element, change the values to "transparent !important" and untoggling "hover"

<img width="327" alt="image" src="https://user-images.githubusercontent.com/33583906/231322047-e51986d1-9699-42a2-b650-57f4fb025d06.png">

https://user-images.githubusercontent.com/33583906/231321925-42c877cf-ce21-4c77-8860-dfb9f07e51d1.mov

### Tamagui Version

```markdown
1.14.3
```

### Reproduction

```markdown
https://codesandbox.io/p/sandbox/wizardly-lovelace-w7ef8w?file=%2Fpackages%2Fapp%2Ffeatures%2Fhome%2Fscreen.tsx&selection=%5B%7B%22endColumn%22%3A53%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A53%2C%22startLineNumber%22%3A25%7D%5D
```

### System Info

```markdown
CodeSandbox and everywhere I guess
```

**Comment by natew** [comment]
this should be fixed

**Comment by holubiev** [comment]
> this should be fixed

I still have this issue in 1.135.2. For now removing _backgroundPress_ etc. from a component theme did help.
