### ISSUE TITLE
Quick Start vercel deploy not working

### ISSUE THREAD

**Issue by ahmednrana** [tamagui/tamagui#99]
**Describe the bug**
I am trying out tamagui

1. I tried using **Quick Start** From this link [https://tamagui.dev/docs/intro/installation](https://tamagui.dev/docs/intro/installation)
2. Click on deploy to vercel button to deploy **[create-tamagui-app](https://tamagui.dev/docs/guides/create-tamagui-app)**
3. It asks to create a new repo. 
4. The deployment to vercel fails with the following error
```
[16:46:52.925] Cloning github.com/ahmednrana/test-tamagui (Branch: main, Commit: d997015)
[16:46:53.709] Cloning completed: 783.131ms
[16:46:53.752] Error: The specified Root Directory "next-expo-solito/apps/next" does not exist. Please update your Project Settings. Learn More: https://vercel.com/docs/build-step#root-directory

```
<img width="435" alt="image" src="https://user-images.githubusercontent.com/21101759/173820093-c8c2bef7-3929-434d-844f-077fab9b93b5.png">

**Comment by natew** [comment]
Thanks, should be fixed here deb5b7d1e62df692b920e38e1406fc83d57cd2a6

**Comment by ahmednrana** [comment]
Just tried. Still the same error
<img width="431" alt="image" src="https://user-images.githubusercontent.com/21101759/174071056-fe4f564e-f7e9-495c-bf7e-33f8b82882ee.png">
